import {
  Globe,
  Building2,
  Network,
  Cloud,
  Code2,
  Users,
  Layers,
  Smartphone,
  MonitorSmartphone,
  Database,
  ShieldCheck,
  Sparkles,
  Wand2,
  MessageSquareCode,
  Brain,
  Bot,
  Plug,
  type LucideIcon,
} from "lucide-react";
import type { SubServicePageProps } from "@/components/site/SubServicePage";

type Entry = Omit<SubServicePageProps, "title"> & { title: string };

export const subServices: Record<string, Entry> = {
  // ── By Team Expertise ────────────────────────────────────────
  "global-capability-center": {
    eyebrow: "Global Capability Center",
    title: "Stand up your GCC in India — without the 2-year build.",
    lede: "We help global enterprises launch and scale captive engineering centers in India — from legal entity and real estate to a 50-engineer org chart that ships in week one.",
    accent: "var(--brand-blue)",
    Icon: Globe,
    heroStats: [
      { value: "12 wks", label: "Avg. GCC setup" },
      { value: "50–500", label: "Engineers scaled" },
      { value: "40%", label: "Lower TCO vs. onshore" },
      { value: "100%", label: "Knowledge retention" },
    ],
    whoFor: [
      "Series C+ SaaS or enterprise platforms tired of paying agency markups.",
      "Global CIOs consolidating fragmented vendor relationships into one captive center.",
      "PE-backed firms building portfolio-wide shared engineering services.",
      "Enterprises de-risking single-vendor dependency on outsourcing partners.",
    ],
    capabilities: [
      { title: "Entity & compliance setup", body: "Private limited incorporation, GST, STPI, SEZ, ESI/PF, and payroll wired up in under 8 weeks." },
      { title: "Office & infrastructure", body: "Grade-A real estate, network, security zones, and badge access — turnkey from day one." },
      { title: "Engineering hiring", body: "Top-of-funnel recruiting through senior-level execs, all on our 4-stage technical bar." },
      { title: "Operating model design", body: "Squad structures, ceremonies, RACI, and global handoff playbooks tuned to your HQ." },
      { title: "Security & compliance", body: "SOC 2, ISO 27001, DPDP, and HIPAA-aligned controls embedded from the first commit." },
      { title: "Build-Operate-Transfer", body: "We run it for 24 months, then transfer the entity, leases, and team — fully owned by you." },
    ],
    outcomes: [
      { metric: "$3.2M", label: "Annual savings", context: "Fortune 500 retailer replaced 3 outsourcing vendors with a 90-person GCC in Hyderabad." },
      { metric: "11 weeks", label: "Time to first ship", context: "PE-backed SaaS shipped their first feature out of the new GCC in under 3 months." },
      { metric: "94%", label: "12-month retention", context: "Across 4 active GCCs we operate, attrition stays well below India industry average." },
    ],
    process: [
      { title: "Strategy & sizing", body: "2-week diagnostic: cost model, talent map, location trade-offs, and 24-month headcount plan." },
      { title: "Entity & space", body: "Incorporation, registrations, office fit-out, and tech infra ready before any hire lands." },
      { title: "Hire & launch", body: "Squad-by-squad ramp with a senior engineering leader embedded from day one." },
      { title: "Operate & transfer", body: "We run, govern, and report. When you're ready, the whole org transfers to your books." },
    ],
    tech: ["Hyderabad", "Bengaluru", "Pune", "Chennai", "Gurugram", "SEZ", "STPI", "GIFT City"],
    faqs: [
      { q: "Can we start with just 10 engineers?", a: "Yes — we have a 'micro-GCC' model that starts at 10 and scales without re-architecting the entity." },
      { q: "Do we own the IP from day one?", a: "Always. Every contract, codebase, and contributor agreement assigns IP directly to your parent entity." },
      { q: "How fast can you transfer the entity?", a: "Build-Operate-Transfer typically completes in 18–24 months; we've done it in 12 when needed." },
    ],
    siblingLinks: [
      { to: "/services/it-staffing", label: "IT Staffing" },
      { to: "/services/product-engineering", label: "Product Engineering" },
      { to: "/services/offshore-development", label: "Offshore Development" },
    ],
  },

  "offshore-development": {
    eyebrow: "Offshore Development",
    title: "Offshore teams that ship like your in-house team.",
    lede: "Senior offshore engineering pods that integrate directly with your stand-ups, codebase, and release train — no agency middle layer, no time-zone games.",
    accent: "var(--brand-green)",
    Icon: Building2,
    heroStats: [
      { value: "60%", label: "Avg. cost reduction" },
      { value: "4 hrs", label: "Daily overlap with US" },
      { value: "9 yrs", label: "Avg. engineer tenure" },
      { value: "2 wks", label: "Time to first PR" },
    ],
    whoFor: [
      "US/EU product teams under hiring freezes that still need to ship.",
      "Scale-ups burning runway on local senior salaries.",
      "CTOs who tried offshore once and got burned by quality.",
      "Enterprises needing 24/7 follow-the-sun development coverage.",
    ],
    capabilities: [
      { title: "Dedicated pods", body: "3–15 engineer squads with a senior tech lead — same team, every sprint." },
      { title: "Time-zone overlap", body: "Engineers shift their day to give you 4+ hours of real-time collaboration." },
      { title: "Codebase ownership", body: "Pods own modules end-to-end — PRs, on-call, incident response, the lot." },
      { title: "Onshore liaison", body: "A US- or EU-based engagement lead handles escalations and weekly reviews." },
      { title: "Security & IP", body: "Locked-down environments, signed NDAs, and full IP assignment from every contributor." },
      { title: "Knowledge transfer", body: "Documented runbooks, recorded onboarding, and a 30-day shadow period — no key-person risk." },
    ],
    outcomes: [
      { metric: "62%", label: "Lower fully-loaded cost", context: "Compared to equivalent senior hires in SF/NYC/London markets." },
      { metric: "4.8/5", label: "Client NPS", context: "Averaged across 30+ active offshore engagements over the past 24 months." },
      { metric: "0", label: "Pod-level escalations", context: "In our last 12 months — disputes are caught and resolved at the daily standup level." },
    ],
    process: [
      { title: "Scope & shape", body: "We map the work, define success metrics, and propose a pod composition." },
      { title: "Hand-pick the pod", body: "You meet and approve every engineer before they join your team." },
      { title: "Onboard & shadow", body: "30 days of structured ramp, codebase walkthroughs, and pair-programming." },
      { title: "Operate & grow", body: "Weekly reviews, monthly retros, quarterly capacity planning — adjust as the roadmap moves." },
    ],
    faqs: [
      { q: "Can we interview the engineers?", a: "Yes. You approve every hire — we never assign engineers without your sign-off." },
      { q: "What if an engineer underperforms?", a: "We replace them within 2 weeks at our cost, with a fully ramped substitute." },
      { q: "Do we sign per-engineer contracts?", a: "No — one master agreement covers the pod, with transparent monthly invoicing per seat." },
    ],
    siblingLinks: [
      { to: "/services/it-staffing", label: "IT Staffing" },
      { to: "/services/product-engineering", label: "Product Engineering" },
      { to: "/services/global-capability-center", label: "GCC" },
    ],
  },

  "it-outsourcing": {
    eyebrow: "IT Outsourcing",
    title: "Outsource IT — not your standards.",
    lede: "End-to-end IT outsourcing for enterprises that want lower run-cost without surrendering quality, security posture, or institutional knowledge.",
    accent: "var(--brand-orange)",
    Icon: Network,
    heroStats: [
      { value: "35–55%", label: "Run-cost reduction" },
      { value: "99.95%", label: "Avg. SLA delivered" },
      { value: "24/7", label: "Operations coverage" },
      { value: "ITIL v4", label: "Aligned processes" },
    ],
    whoFor: [
      "Mid-market and enterprise CIOs consolidating fragmented IT spend.",
      "Companies post-M&A looking to unify divergent IT operations.",
      "Regulated industries needing audited, SLA-backed managed services.",
      "Internal IT teams stretched thin by tier-1 ticket volume.",
    ],
    capabilities: [
      { title: "Application management", body: "L1–L3 support, enhancements, upgrades, and modernization across legacy and modern stacks." },
      { title: "Infrastructure management", body: "Cloud, on-prem, hybrid — monitored, patched, and incident-managed against tight SLAs." },
      { title: "Service desk & ITSM", body: "Multi-channel L1/L2 desk built on ServiceNow, Jira, or Freshservice — branded to look like yours." },
      { title: "DevOps & SRE", body: "Pipelines, observability, on-call rotations, and post-mortem culture — owned end-to-end." },
      { title: "Security operations", body: "24/7 SOC, vulnerability management, and incident response with documented playbooks." },
      { title: "Vendor governance", body: "Single throat to choke — we manage your sub-vendors and consolidate reporting upward." },
    ],
    outcomes: [
      { metric: "47%", label: "TCO reduction", context: "Mid-market manufacturer consolidated 6 IT vendors into a single Pure Tech contract." },
      { metric: "99.97%", label: "Uptime delivered", context: "12-month rolling SLA across critical apps for a Tier-1 BFSI client." },
      { metric: "<8 min", label: "Mean response", context: "P1 ticket acknowledgement, measured at the service desk level." },
    ],
    process: [
      { title: "Discovery & due diligence", body: "Inventory, SLA baseline, risk register, and a clean-room transition plan." },
      { title: "Knowledge transfer", body: "Reverse shadowing, runbook capture, and certified handover from the incumbent." },
      { title: "Steady state", body: "Operate to SLA with monthly governance reviews and quarterly value engineering." },
      { title: "Transform", body: "Year-over-year continuous improvement — automation, consolidation, modernization." },
    ],
    faqs: [
      { q: "Can you take over from an incumbent mid-contract?", a: "Yes — we specialize in clean transitions with zero SLA degradation during cutover." },
      { q: "Are pricing models flexible?", a: "We offer T&M, fixed-price, outcome-based, and hybrid models — chosen per workstream." },
      { q: "How do you handle compliance audits?", a: "We carry SOC 2 Type II, ISO 27001, and provide audit-ready evidence on demand." },
    ],
    siblingLinks: [
      { to: "/services/it-staffing", label: "IT Staffing" },
      { to: "/services/cloud-computing", label: "Cloud Computing" },
      { to: "/services/cybersecurity", label: "Cybersecurity" },
    ],
  },

  "cloud-computing": {
    eyebrow: "Cloud Computing",
    title: "Cloud done by engineers, not slide-makers.",
    lede: "Cloud strategy, migration, and FinOps for teams that want to ship faster, spend less, and stop renting consultants who've never run production.",
    accent: "var(--brand-blue)",
    Icon: Cloud,
    heroStats: [
      { value: "200+", label: "Cloud migrations" },
      { value: "32%", label: "Avg. spend reduction" },
      { value: "3 clouds", label: "AWS, Azure, GCP" },
      { value: "SRE-led", label: "Every engagement" },
    ],
    whoFor: [
      "Teams stuck mid-migration with stalled lift-and-shift programs.",
      "CFOs alarmed by cloud bills with no clear unit economics.",
      "Engineering leaders modernizing monoliths to containerized workloads.",
      "Multi-cloud organizations needing a single observability and FinOps layer.",
    ],
    capabilities: [
      { title: "Cloud strategy & landing zones", body: "Multi-account, multi-region landing zones with guardrails baked in — not bolted on." },
      { title: "Migration & modernization", body: "Rehost, replatform, refactor — chosen per workload, executed in fixed-price waves." },
      { title: "Kubernetes & containers", body: "EKS, AKS, GKE — production-grade clusters with mesh, policy, and cost controls." },
      { title: "FinOps & cost engineering", body: "Tagging, anomaly detection, RIs/SPs, and showback dashboards that actually get read." },
      { title: "SRE & observability", body: "SLOs, error budgets, distributed tracing, and on-call rotations — not just dashboards." },
      { title: "Cloud security posture", body: "CSPM, CIEM, IaC scanning, and continuous compliance to CIS, NIST, and SOC 2." },
    ],
    outcomes: [
      { metric: "$1.4M", label: "Annual cloud savings", context: "FinOps engagement for a high-growth SaaS — recovered in the first 60 days." },
      { metric: "11×", label: "Faster deploys", context: "Modernization from monolith to EKS for a logistics platform — daily releases unlocked." },
      { metric: "Zero", label: "Failed cutovers", context: "Across our last 40 migrations — every wave landed on the planned weekend." },
    ],
    process: [
      { title: "Assess", body: "Workload discovery, dependency mapping, cost baseline, and a wave plan." },
      { title: "Foundation", body: "Landing zone, network, identity, observability, and FinOps — before any workload moves." },
      { title: "Migrate", body: "Wave-based execution with rollback at every step. Production cutovers run by SREs." },
      { title: "Optimize", body: "Continuous right-sizing, reservation strategy, and architectural improvements." },
    ],
    tech: ["AWS", "Azure", "GCP", "Kubernetes", "Terraform", "Crossplane", "Datadog", "Grafana", "OpenTelemetry"],
    faqs: [
      { q: "Do you lock us into one cloud?", a: "No. We design for portability where it matters and embrace cloud-native services where it doesn't." },
      { q: "Can you reduce our existing cloud bill?", a: "Typically 20–35% in the first 90 days through right-sizing, commitments, and idle resource elimination." },
      { q: "Do you do on-prem too?", a: "Yes — hybrid landing zones and on-prem Kubernetes when regulation or latency demands it." },
    ],
    siblingLinks: [
      { to: "/services/it-outsourcing", label: "IT Outsourcing" },
      { to: "/services/cloud-infrastructure", label: "Cloud & Infrastructure" },
      { to: "/services/cybersecurity", label: "Cybersecurity" },
    ],
  },

  // ── Offering ─────────────────────────────────────────────────
  "software-development": {
    eyebrow: "Software Development",
    title: "World-class software, shipped on a senior bar.",
    lede: "Full-stack software development for products that need to feel fast, look elegant, and hold up to enterprise scrutiny.",
    accent: "var(--brand-blue)",
    Icon: Code2,
    heroStats: [
      { value: "500+", label: "Products shipped" },
      { value: "9 yrs", label: "Avg. tenure" },
      { value: "2 wks", label: "Sprint cadence" },
      { value: "94%", label: "On-time delivery" },
    ],
    whoFor: [
      "Startups that need a small senior team to ship v1 in 12 weeks.",
      "Enterprises modernizing legacy applications under regulatory pressure.",
      "Product leaders rebuilding from a successful POC to production scale.",
      "Companies whose internal teams need surge capacity for a hard roadmap quarter.",
    ],
    capabilities: [
      { title: "Full-stack engineering", body: "TypeScript, React, Node, Go, Python — chosen for the problem, not the resume." },
      { title: "API & service design", body: "REST, GraphQL, gRPC, event-driven — designed for the consumers, versioned for the future." },
      { title: "Database & data modeling", body: "Postgres, MySQL, MongoDB, Redis — schemas that survive product pivots." },
      { title: "Testing & quality", body: "Unit, integration, contract, and E2E — coverage targets that match the risk profile." },
      { title: "Performance engineering", body: "P95 latency budgets, load testing, profiling — not 'it works on my machine'." },
      { title: "Code review & mentorship", body: "Senior engineers review every PR — quality compounds across the engagement." },
    ],
    outcomes: [
      { metric: "8 wks", label: "MVP to production", context: "Average for greenfield SaaS products built by a 4-engineer Pure Tech pod." },
      { metric: "P95 < 120ms", label: "API latency", context: "Standard delivered on every API-first engagement we run." },
      { metric: "85%+", label: "Test coverage", context: "Default on every codebase we ship — measured at the branch protection level." },
    ],
    process: [
      { title: "Discovery", body: "Two-week shaping: success metrics, technical risks, architecture spike, and a written plan." },
      { title: "Build", body: "Two-week sprints, Friday demos, written changelogs, and a green main branch every day." },
      { title: "Ship", body: "Phased rollouts, feature flags, observability before features, and zero-downtime cutovers." },
      { title: "Evolve", body: "Post-launch capacity for performance, growth experiments, and roadmap iteration." },
    ],
    tech: ["TypeScript", "React", "Next.js", "Node.js", "Go", "Python", "Postgres", "Kubernetes", "AWS"],
    faqs: [
      { q: "Will you use our stack or yours?", a: "Yours — we adapt to your stack rather than forcing ours. Our engineers are stack-fluent." },
      { q: "How small can the team be?", a: "We can start with a single senior engineer plus part-time tech lead — and scale up as needed." },
      { q: "Who owns the code?", a: "You do — from the first commit. Our contributor agreements assign all IP to you." },
    ],
    siblingLinks: [
      { to: "/services/product-engineering", label: "Product Engineering" },
      { to: "/services/web-application-development", label: "Web Application Dev" },
      { to: "/services/mobile-app-development", label: "Mobile App Dev" },
    ],
  },

  "remote-teams": {
    eyebrow: "Remote Teams",
    title: "Pre-vetted remote development teams, on tap.",
    lede: "Hire entire pre-vetted engineering teams — not a stack of freelancers — that integrate cleanly into your processes from day one.",
    accent: "var(--brand-orange)",
    Icon: Users,
    heroStats: [
      { value: "180+", label: "Engineers on bench" },
      { value: "5–10 days", label: "Team match" },
      { value: "Top 3%", label: "Talent bar" },
      { value: "0", label: "Bait-and-switch" },
    ],
    whoFor: [
      "Founders who need a team without spending six months on interviews.",
      "Product leaders needing a squad ready to ship — not just a CV pile.",
      "Companies tired of staffing agencies that ship resumes, not results.",
      "Scale-ups standing up a new product line outside the core team.",
    ],
    capabilities: [
      { title: "Pre-formed squads", body: "Engineers who've worked together before — no team-formation friction." },
      { title: "Tech-lead included", body: "A senior lead per pod, included in the rate — no need to hire one separately." },
      { title: "Process alignment", body: "We adopt your Jira, your Git flow, your DoD — not the other way around." },
      { title: "Onboarding playbook", body: "30-60-90 day plan, codebase walkthrough, shadow rotations, paired with your team." },
      { title: "Flexible scaling", body: "Add or pause seats with 30 days notice — capacity matches your roadmap." },
      { title: "Single-point-of-contact", body: "A US/EU engagement lead handles all coordination — no PM tax on your team." },
    ],
    outcomes: [
      { metric: "9 days", label: "Avg. time to start", context: "From signed MSA to first standup, measured across our last 50 pod deployments." },
      { metric: "97%", label: "12-month renewal", context: "Pods that complete an initial engagement and continue into year two." },
      { metric: "0%", label: "Engineer swap rate", context: "Once a pod is approved by you, the team stays — no rotations without your consent." },
    ],
    process: [
      { title: "Brief", body: "30-minute call to capture skills, stack, timezone overlap, and team chemistry needs." },
      { title: "Match", body: "We propose a 3–8 person squad within 5 business days — you interview and approve every member." },
      { title: "Onboard", body: "Structured 30-day ramp with your team, including codebase deep-dives and pair programming." },
      { title: "Ship", body: "Weekly reviews, monthly retros, and quarterly capacity planning." },
    ],
    faqs: [
      { q: "Are these freelancers?", a: "No — every engineer is a full-time Pure Technology employee with benefits and tenure." },
      { q: "Can we hire them directly later?", a: "Yes — after 12 months, we offer a fair conversion path with a flat transfer fee." },
      { q: "What timezones do you cover?", a: "We have engineers across India, with shifts arranged for US East, US West, EU, and APAC overlap." },
    ],
    siblingLinks: [
      { to: "/services/it-staffing", label: "IT Staff Augmentation" },
      { to: "/services/offshore-development", label: "Offshore Development" },
      { to: "/services/product-engineering", label: "Product Engineering" },
    ],
  },

  "web-application-development": {
    eyebrow: "Web Application Development",
    title: "Web apps that feel native, scale globally.",
    lede: "Build modern, intuitive, and seamless web applications using React, Next.js, and a senior team that takes performance and accessibility seriously.",
    accent: "var(--brand-green)",
    Icon: Layers,
    heroStats: [
      { value: "200+", label: "Web apps shipped" },
      { value: "<1s", label: "Avg. LCP delivered" },
      { value: "WCAG AA", label: "Default standard" },
      { value: "PWA-ready", label: "Where it makes sense" },
    ],
    whoFor: [
      "Product teams modernizing a legacy jQuery or AngularJS app.",
      "SaaS founders launching v1 of a customer-facing product.",
      "Enterprises building internal tools that need to feel as good as consumer apps.",
      "Marketing teams shipping landing pages that need to A/B at sub-second speed.",
    ],
    capabilities: [
      { title: "React & Next.js apps", body: "App Router, server components, edge runtime — used pragmatically, not for buzzword bingo." },
      { title: "Design systems", body: "Token-driven systems built on Radix, shadcn, or your own — documented and tested." },
      { title: "Performance budgets", body: "Core Web Vitals SLOs, bundle analysis, and edge caching as a first-class concern." },
      { title: "Accessibility", body: "WCAG 2.1 AA by default — keyboard nav, screen-reader semantics, and contrast audits." },
      { title: "Auth, billing, integrations", body: "Auth0, Clerk, Stripe, Segment — wired in cleanly, not bolted on." },
      { title: "Internationalization", body: "i18n routing, RTL, locale-aware formatting, and content workflows for marketing teams." },
    ],
    outcomes: [
      { metric: "0.6s", label: "LCP achieved", context: "Replatformed a 4s Angular dashboard to a Next.js + edge stack." },
      { metric: "31%", label: "Conversion lift", context: "Performance + UX overhaul on a high-traffic D2C site within 90 days of go-live." },
      { metric: "100/100", label: "Lighthouse scores", context: "Delivered on the marketing surfaces of our last 12 launches." },
    ],
    process: [
      { title: "Shape", body: "Information architecture, design tokens, performance budget, and a clickable prototype." },
      { title: "Build", body: "Component-driven development, Storybook-first, with E2E coverage on critical paths." },
      { title: "Launch", body: "Phased rollout, real-user monitoring from day one, and a 30-day stabilization sprint." },
      { title: "Grow", body: "Experimentation framework, growth instrumentation, and ongoing performance reviews." },
    ],
    tech: ["React", "Next.js", "TypeScript", "Tailwind", "Radix", "tRPC", "Tanstack Query", "Vercel", "Cloudflare"],
    faqs: [
      { q: "Do you use Next.js for everything?", a: "No — Remix, Astro, SvelteKit, or vanilla React all show up depending on the problem." },
      { q: "Can you work with our existing design system?", a: "Absolutely — we adapt to your tokens and patterns, or help you build one if you don't have one." },
      { q: "Do you handle SEO?", a: "Technical SEO is built in. Content SEO requires your marketing input — we partner closely." },
    ],
    siblingLinks: [
      { to: "/services/software-development", label: "Software Development" },
      { to: "/services/front-end-development", label: "Front-End Development" },
      { to: "/services/mobile-app-development", label: "Mobile App Dev" },
    ],
  },

  "mobile-app-development": {
    eyebrow: "Mobile App Development",
    title: "Mobile apps customers actually keep on their home screen.",
    lede: "Native iOS, Android, and React Native apps designed for retention, not just App Store screenshots.",
    accent: "var(--brand-orange)",
    Icon: Smartphone,
    heroStats: [
      { value: "120+", label: "Apps shipped" },
      { value: "4.7★", label: "Avg. store rating" },
      { value: "<2%", label: "Crash-free regression" },
      { value: "Day-0", label: "Privacy compliance" },
    ],
    whoFor: [
      "D2C brands launching a mobile-first commerce experience.",
      "Fintech & health teams needing offline-capable, secure native apps.",
      "Enterprises shipping internal field-force or operations apps.",
      "Product teams replacing aging React Native or Flutter codebases.",
    ],
    capabilities: [
      { title: "Native iOS (Swift/SwiftUI)", body: "Modern Apple platform development — including watchOS and iPadOS where relevant." },
      { title: "Native Android (Kotlin/Compose)", body: "Material 3, Jetpack Compose, and modern Android architecture components." },
      { title: "React Native / Expo", body: "When code sharing makes sense — with native modules where it doesn't." },
      { title: "Offline-first sync", body: "Local-first data models, conflict resolution, and bandwidth-aware sync for real-world networks." },
      { title: "Mobile observability", body: "Sentry, Firebase, Datadog Mobile RUM — wired in before launch." },
      { title: "App Store strategy", body: "Submission, review responses, ASO basics, and phased rollouts via TestFlight & Internal Testing." },
    ],
    outcomes: [
      { metric: "47%", label: "Higher 30-day retention", context: "Rebuilt a hybrid app as native iOS/Android — same features, dramatically better feel." },
      { metric: "<0.3%", label: "Crash-free sessions", context: "Held across our last 8 production mobile apps for 12+ months." },
      { metric: "5 days", label: "Avg. store review time", context: "Submission packaging and review responses handled by our mobile leads." },
    ],
    process: [
      { title: "Define", body: "Platform strategy (native vs. RN), design system audit, and a measurable launch metric." },
      { title: "Design", body: "Platform-idiomatic UX — not 'web in a webview' — with prototypes tested on real devices." },
      { title: "Build & test", body: "Device matrix testing, automated UI tests, and beta cohorts via TestFlight/Internal Testing." },
      { title: "Launch & iterate", body: "Phased rollouts, crash triage, and post-launch retention experiments." },
    ],
    tech: ["Swift", "SwiftUI", "Kotlin", "Jetpack Compose", "React Native", "Expo", "Firebase", "Sentry"],
    faqs: [
      { q: "Native or React Native?", a: "We help you decide based on team, budget, performance needs, and platform-specific feature reliance." },
      { q: "Can you take over an existing codebase?", a: "Yes — we audit, stabilize, and incrementally modernize. Greenfield isn't always necessary." },
      { q: "Do you handle compliance (HIPAA, PCI)?", a: "Yes — we ship HIPAA-aligned and PCI-aware apps with full documentation for your audit team." },
    ],
    siblingLinks: [
      { to: "/services/web-application-development", label: "Web Apps" },
      { to: "/services/product-engineering", label: "Product Engineering" },
      { to: "/services/software-development", label: "Software Development" },
    ],
  },

  "cloud-infrastructure": {
    eyebrow: "Cloud & Infrastructure",
    title: "Infrastructure that ships features — not tickets.",
    lede: "Modern cloud and infrastructure engineering: landing zones, Kubernetes, IaC, observability, and an SRE culture that lets product teams move fast safely.",
    accent: "var(--brand-blue)",
    Icon: Cloud,
    heroStats: [
      { value: "150+", label: "Infra projects" },
      { value: "99.99%", label: "SLO achievable" },
      { value: "100%", label: "IaC coverage" },
      { value: "GitOps", label: "By default" },
    ],
    whoFor: [
      "Engineering orgs whose deploys take an afternoon instead of a coffee.",
      "Teams whose 'production' is a snowflake EC2 instance no one wants to touch.",
      "Companies adopting Kubernetes and getting stuck on day-2 operations.",
      "CTOs needing audit-grade documentation for SOC 2, ISO, or HITRUST.",
    ],
    capabilities: [
      { title: "Landing zones", body: "Multi-account AWS/Azure/GCP foundations with guardrails, SCPs, and policy-as-code." },
      { title: "Kubernetes platforms", body: "EKS/AKS/GKE clusters with service mesh, policy, autoscaling, and cost-aware scheduling." },
      { title: "IaC & GitOps", body: "Terraform, Crossplane, Argo CD, Flux — every change reviewed, every drift detected." },
      { title: "CI/CD pipelines", body: "Trunk-based development, ephemeral environments, and progressive delivery via flags." },
      { title: "Observability", body: "Logs, metrics, traces, and SLO dashboards that engineers actually open." },
      { title: "Disaster recovery", body: "RTO/RPO-driven backup, multi-region active-passive, and tested runbooks." },
    ],
    outcomes: [
      { metric: "12×", label: "Faster deploys", context: "From bi-weekly releases to dozens per day for a Series C fintech." },
      { metric: "63%", label: "MTTR reduction", context: "After rolling out SLO-based on-call and trace-driven incident response." },
      { metric: "100%", label: "Audit pass", context: "Across SOC 2 Type II audits where we owned the underlying infra." },
    ],
    process: [
      { title: "Audit", body: "Current-state assessment: reliability, cost, security posture, and developer experience." },
      { title: "Foundation", body: "Landing zone, identity, network, observability, and CI/CD baseline before workloads move." },
      { title: "Migrate & modernize", body: "Wave-based workload migration with automated rollback at every step." },
      { title: "Run & improve", body: "SRE-led operations with monthly reliability reviews and quarterly platform upgrades." },
    ],
    tech: ["AWS", "Azure", "GCP", "Kubernetes", "Terraform", "Crossplane", "Argo CD", "Datadog", "Grafana", "Vault"],
    faqs: [
      { q: "Can you run platform engineering for us long-term?", a: "Yes — we offer fully managed platform engineering with 24/7 on-call coverage." },
      { q: "Do we need to be on the cloud already?", a: "No — we run greenfield landing zones and we run modernization out of legacy data centers." },
      { q: "How do you handle compliance evidence?", a: "Automated evidence collection wired into the CI/CD pipeline — auditors get a portal, not emails." },
    ],
    siblingLinks: [
      { to: "/services/cloud-computing", label: "Cloud Computing" },
      { to: "/services/it-outsourcing", label: "IT Outsourcing" },
      { to: "/services/cybersecurity", label: "Cybersecurity" },
    ],
  },

  "front-end-development": {
    eyebrow: "Front End Development",
    title: "Front-ends that feel inevitable.",
    lede: "Pixel-perfect, accessible, and fast front-ends — built by engineers who treat the browser as a first-class platform.",
    accent: "var(--brand-red)",
    Icon: MonitorSmartphone,
    heroStats: [
      { value: "300+", label: "Front-ends shipped" },
      { value: "WCAG AA", label: "Default standard" },
      { value: "<100ms", label: "INP target" },
      { value: "Top 1%", label: "Core Web Vitals" },
    ],
    whoFor: [
      "Product teams whose front-end has accumulated a decade of jQuery and tech debt.",
      "Design-led companies whose engineering can't keep up with Figma.",
      "Marketing teams shipping high-traffic landing pages that need to A/B fast.",
      "Enterprises that want consumer-grade UX in their internal tools.",
    ],
    capabilities: [
      { title: "Design system engineering", body: "Token-driven systems on Radix, shadcn, or custom primitives — fully accessible, fully themed." },
      { title: "React & framework expertise", body: "React, Next.js, Remix, Astro, SvelteKit — picked for the problem, never for the trend." },
      { title: "Animation & motion", body: "Framer Motion, GSAP, view transitions — used to communicate, not to decorate." },
      { title: "Accessibility audits", body: "WCAG 2.1 AA verification with screen readers, keyboard, and zoom — not just axe-core." },
      { title: "Performance engineering", body: "Bundle splitting, critical CSS, edge rendering, and Core Web Vitals SLOs." },
      { title: "Design-to-code workflow", body: "Figma tokens piped into code, with handoff loops that designers and engineers both love." },
    ],
    outcomes: [
      { metric: "0.4s", label: "LCP achieved", context: "Re-engineered a SaaS dashboard front-end — same product, fundamentally different feel." },
      { metric: "+22%", label: "Activation lift", context: "Replaced a 3-step onboarding with a faster, animated flow — measured at the cohort level." },
      { metric: "100%", label: "WCAG AA pass", context: "Default across all enterprise dashboards we've shipped in the last 24 months." },
    ],
    process: [
      { title: "Audit", body: "Performance, accessibility, and design system audits — with a prioritized backlog." },
      { title: "Foundation", body: "Tokens, primitives, and Storybook — the substrate everything else builds on." },
      { title: "Ship", body: "Component-by-component delivery with E2E coverage and visual regression tests." },
      { title: "Optimize", body: "Real-user monitoring, regular Core Web Vitals reviews, and motion polish." },
    ],
    tech: ["React", "Next.js", "TypeScript", "Tailwind", "Radix", "Framer Motion", "Storybook", "Playwright"],
    faqs: [
      { q: "Do you do design too?", a: "We partner with your designers or bring in design partners — we don't pretend to be a design studio." },
      { q: "Can you keep our existing back-end?", a: "Yes — we're front-end specialists, but we know how to consume any reasonable API." },
      { q: "How do you handle browser support?", a: "We define a baseline with you (typically last 2 of evergreen + iOS Safari) and test there continuously." },
    ],
    siblingLinks: [
      { to: "/services/web-application-development", label: "Web Application Dev" },
      { to: "/services/mobile-app-development", label: "Mobile App Dev" },
      { to: "/services/software-development", label: "Software Development" },
    ],
  },

  "data-engineering": {
    eyebrow: "Data Engineering",
    title: "Data pipelines you can bet a quarterly report on.",
    lede: "Modern data engineering — warehouses, lakes, streams, and the governance layer — built so analysts and AI teams stop arguing about which number is real.",
    accent: "var(--brand-green)",
    Icon: Database,
    heroStats: [
      { value: "60+", label: "Data platforms shipped" },
      { value: "<5 min", label: "Avg. SLA freshness" },
      { value: "100%", label: "Lineage coverage" },
      { value: "dbt-native", label: "By default" },
    ],
    whoFor: [
      "Companies whose dashboards disagree depending on who opens them.",
      "Analytics teams blocked on raw access while data engineering rewrites pipelines.",
      "AI teams needing a feature store and clean training data.",
      "CFOs needing audited, reconciled data for board reporting and compliance." ,
    ],
    capabilities: [
      { title: "Modern warehouse", body: "Snowflake, BigQuery, Databricks, Redshift — architected for cost, performance, and governance." },
      { title: "ELT & ingestion", body: "Fivetran, Airbyte, custom CDC, and event pipelines — observable, idempotent, and replayable." },
      { title: "dbt-first modeling", body: "Layered models, tests, exposures, and semantic layer — analysts can self-serve safely." },
      { title: "Streaming pipelines", body: "Kafka, Flink, Materialize, and Snowpipe — for use cases where seconds matter." },
      { title: "Governance & lineage", body: "Catalog, lineage, PII tagging, and access controls — wired into the warehouse, not bolted on." },
      { title: "Feature stores for ML", body: "Tecton, Feast, or warehouse-native — supporting both batch training and real-time inference." },
    ],
    outcomes: [
      { metric: "43%", label: "Warehouse spend cut", context: "Workload tuning + warehouse rightsizing on a Snowflake bill running 7 figures." },
      { metric: "2 min", label: "Pipeline freshness", context: "Reduced from a 6-hour batch to a sub-2-minute CDC stream for a fintech." },
      { metric: "100%", label: "Lineage coverage", context: "Every model traced from source to dashboard — default on every engagement." },
    ],
    process: [
      { title: "Map", body: "Source inventory, consumer interviews, freshness needs, and a target architecture." },
      { title: "Foundation", body: "Warehouse, ingestion, security, and dbt baseline — set up for the next 5 years, not the next sprint." },
      { title: "Model", body: "Layered semantic modeling, tests, contracts, and a single source of truth per domain." },
      { title: "Operate", body: "Pipeline observability, on-call rotations, and quarterly model reviews." },
    ],
    tech: ["Snowflake", "BigQuery", "Databricks", "dbt", "Airflow", "Fivetran", "Kafka", "Materialize", "Tecton"],
    faqs: [
      { q: "Do we need to switch warehouses?", a: "Usually not — we work with what you have, and migrate only when the ROI is clear." },
      { q: "Can you support our analytics team?", a: "Yes — we run enablement, code reviews, and embedded analytics engineering pods." },
      { q: "How do you handle PII and compliance?", a: "Column-level masking, row-level security, and tagged lineage — designed for SOC 2, GDPR, and HIPAA." },
    ],
    siblingLinks: [
      { to: "/services/ai-solutions", label: "AI Solutions" },
      { to: "/services/cloud-infrastructure", label: "Cloud & Infrastructure" },
      { to: "/services/software-development", label: "Software Development" },
    ],
  },

  "cybersecurity": {
    eyebrow: "Cybersecurity",
    title: "Security that ships with your product — not after it.",
    lede: "Application security, cloud security, and SOC services for teams that need real defense — not just a clean Vanta dashboard.",
    accent: "var(--brand-red)",
    Icon: ShieldCheck,
    heroStats: [
      { value: "24/7", label: "SOC coverage" },
      { value: "SOC 2 II", label: "Audit-ready" },
      { value: "<15 min", label: "P1 response" },
      { value: "Zero", label: "Disclosed breaches" },
    ],
    whoFor: [
      "Companies preparing for SOC 2, ISO 27001, or HIPAA audits.",
      "Engineering teams shipping faster than their security team can review.",
      "Mid-market firms without a CISO but with enterprise customers.",
      "Regulated industries needing 24/7 SOC and incident response.",
    ],
    capabilities: [
      { title: "Application security", body: "SAST, DAST, dependency scanning, and threat modeling — wired into the CI/CD pipeline." },
      { title: "Cloud security posture", body: "CSPM, CIEM, IaC scanning, and continuous compliance to CIS, NIST, and SOC 2." },
      { title: "Managed SOC", body: "24/7 monitoring, triage, and incident response with documented playbooks per asset class." },
      { title: "Penetration testing", body: "Web, mobile, API, cloud, and network — by OSCP/OSCE-certified offensive engineers." },
      { title: "vCISO services", body: "Fractional CISO leadership for security strategy, board reporting, and audit readiness." },
      { title: "Compliance readiness", body: "SOC 2, ISO 27001, HIPAA, PCI-DSS, DPDP — from gap analysis to certified outcome." },
    ],
    outcomes: [
      { metric: "11 wks", label: "SOC 2 Type I", context: "From kickoff to a clean Type I audit report for a Series B SaaS." },
      { metric: "6 min", label: "MTTD", context: "Mean time to detect on managed SOC — measured against external red-team exercises." },
      { metric: "100%", label: "Audit pass rate", context: "Across the last 18 SOC 2 and ISO 27001 audits where we ran the program." },
    ],
    process: [
      { title: "Assess", body: "Gap analysis against your target framework, threat model, and asset inventory." },
      { title: "Remediate", body: "Prioritized backlog with embedded engineers fixing what tools alone can't." },
      { title: "Operate", body: "24/7 monitoring, regular pen tests, and quarterly tabletop incident exercises." },
      { title: "Certify", body: "Auditor coordination, evidence packaging, and post-audit continuous improvement." },
    ],
    tech: ["Vanta", "Drata", "Wiz", "Snyk", "Semgrep", "CrowdStrike", "Datadog Security", "Burp Suite"],
    faqs: [
      { q: "Can you replace our existing security tooling?", a: "We work with whatever stack you have — and recommend changes only when the ROI is clear." },
      { q: "Do you offer fractional CISO?", a: "Yes — fractional CISO is one of our most-requested services for Series B–C companies." },
      { q: "How fast can you respond to an incident?", a: "Under 15 minutes for P1s. Our SOC carries paged on-call across 3 timezones." },
    ],
    siblingLinks: [
      { to: "/services/cloud-computing", label: "Cloud Computing" },
      { to: "/services/cloud-infrastructure", label: "Cloud & Infrastructure" },
      { to: "/services/it-outsourcing", label: "IT Outsourcing" },
    ],
  },

  // ── Artificial Intelligence ─────────────────────────────────
  "ai-strategy-consulting": {
    eyebrow: "AI Strategy & Consulting",
    title: "AI strategy that survives contact with reality.",
    lede: "A 2–6 week diagnostic that turns AI ambition into a sequenced, measurable roadmap — with the unit economics, risks, and success metrics already worked out.",
    accent: "var(--brand-blue)",
    Icon: Sparkles,
    heroStats: [
      { value: "60+", label: "Strategy engagements" },
      { value: "$2.4M", label: "Avg. value identified" },
      { value: "4 wks", label: "Typical timeline" },
      { value: "CIO-grade", label: "Output quality" },
    ],
    whoFor: [
      "CIOs and Chief AI Officers needing a board-ready AI strategy.",
      "Product leaders with too many AI ideas and not enough sequencing logic.",
      "Companies whose AI POCs aren't converting to production.",
      "PE-backed firms developing AI strategies across portfolio companies.",
    ],
    capabilities: [
      { title: "AI opportunity sizing", body: "Where AI moves the metric, where it's a distraction, and what the realistic ROI window looks like." },
      { title: "Use-case prioritization", body: "Scored backlog by value, feasibility, data readiness, and risk — sequenced into a 12-month plan." },
      { title: "Data & platform readiness", body: "Honest assessment of whether your data, infra, and team can support the AI you want to build." },
      { title: "Build vs. buy analysis", body: "Per use case — open vs. closed models, in-house vs. vendor, with TCO modeling." },
      { title: "Governance & risk", body: "AI governance frameworks aligned to EU AI Act, NIST AI RMF, and your sector regulators." },
      { title: "Org & capability planning", body: "Team design, hiring plan, training program, and operating model for AI at scale." },
    ],
    outcomes: [
      { metric: "$8.7M", label: "Annual value mapped", context: "Strategy engagement for a top-5 Indian bank identified 14 prioritized AI use cases." },
      { metric: "3", label: "POCs killed early", context: "Saved a healthcare client from sinking budget into low-ROI gen-AI initiatives." },
      { metric: "12 wks", label: "Strategy to first ship", context: "From signed engagement to a production AI workload, across our last 6 strategy deals." },
    ],
    process: [
      { title: "Discover", body: "Stakeholder interviews, data inventory, capability audit, and competitive scan." },
      { title: "Frame", body: "Use case longlist, scoring rubric, and prioritization workshop with the executive team." },
      { title: "Sequence", body: "12-month roadmap with milestones, dependencies, and a defined success metric per initiative." },
      { title: "Mobilize", body: "Either hand off to your team or transition into delivery with our AI engineering pods." },
    ],
    faqs: [
      { q: "Do we have to commit to delivery with you afterwards?", a: "No — strategy and delivery are separately commercially negotiated. Many clients hand off to their own teams." },
      { q: "Is this just a slide deck?", a: "No — every engagement includes prototype work, data audits, and a defensible TCO model alongside the deck." },
      { q: "Who runs the engagement?", a: "A senior AI strategist with 10+ years building production AI — backed by domain analysts in your sector." },
    ],
    siblingLinks: [
      { to: "/services/ai-solutions", label: "AI Solutions" },
      { to: "/services/custom-ai-development", label: "Custom AI Development" },
      { to: "/services/ai-integration", label: "AI Integration" },
    ],
  },

  "custom-ai-development": {
    eyebrow: "Custom AI Development",
    title: "Custom AI that fits your data — not the demo.",
    lede: "Bespoke ML and LLM systems trained, fine-tuned, and operated against your data, your constraints, and your customers.",
    accent: "var(--brand-blue)",
    Icon: Wand2,
    heroStats: [
      { value: "40+", label: "Custom AI systems" },
      { value: "12", label: "Production LLMs" },
      { value: "98.6%", label: "Eval pass rate" },
      { value: "MLOps", label: "Built-in" },
    ],
    whoFor: [
      "Companies whose data is their moat — and who refuse to send it to public APIs.",
      "Teams needing specialized models for their domain (legal, medical, financial).",
      "Product leaders building AI-native features that off-the-shelf models can't deliver.",
      "Regulated industries needing fully auditable, in-VPC AI systems.",
    ],
    capabilities: [
      { title: "Model selection & training", body: "Open and closed model evaluation, fine-tuning, LoRA, distillation, and full pretraining where it pays off." },
      { title: "RAG & knowledge systems", body: "Production-grade retrieval over your docs, tickets, code, and structured data — with citations and fallbacks." },
      { title: "Multi-modal AI", body: "Vision, speech, OCR, and structured + unstructured fusion — applied to real customer flows." },
      { title: "Evals & guardrails", body: "Domain-specific eval suites, red-team harnesses, and policy-aware guardrails — wired into CI." },
      { title: "MLOps & inference", body: "Model registry, A/B routing, autoscaling inference, and cost-aware serving on GPU or CPU." },
      { title: "Observability", body: "Token-level tracing, drift detection, and per-feature cost attribution — not just dashboards." },
    ],
    outcomes: [
      { metric: "0", label: "Hallucinations in eval", context: "On medication name extraction for a HealthTech client — measured against a 5k-row gold set." },
      { metric: "₹14 Cr", label: "Annual ops savings", context: "Custom assistant deployment at a top-5 Indian private bank reduced AHT by 37%." },
      { metric: "11×", label: "Faster than human", context: "Clinician chart review accelerated 11× with no drop in accuracy on flagged cases." },
    ],
    process: [
      { title: "Define", body: "Use case, success metric, eval design, and a realistic baseline before any model is trained." },
      { title: "Build", body: "Data pipeline, model selection, fine-tuning loop, and eval harness — versioned end-to-end." },
      { title: "Harden", body: "Guardrails, red-team, cost ceilings, fallbacks, and human-in-the-loop where it matters." },
      { title: "Operate", body: "Inference, observability, drift monitoring, and weekly model improvement cycles." },
    ],
    tech: ["OpenAI", "Anthropic", "Llama", "Mistral", "vLLM", "LangChain", "LlamaIndex", "Weights & Biases", "Modal"],
    faqs: [
      { q: "Do you train models from scratch?", a: "Rarely — fine-tuning, RAG, and adapter methods deliver better ROI for most enterprise problems." },
      { q: "Can the models run in our VPC?", a: "Yes — most engagements run entirely in your cloud account, with no data leaving your boundary." },
      { q: "How do you measure success?", a: "Every engagement starts with a domain-specific eval set; we report against it weekly." },
    ],
    siblingLinks: [
      { to: "/services/ai-solutions", label: "AI Solutions" },
      { to: "/services/generative-ai-development", label: "Generative AI" },
      { to: "/services/ai-agents-development", label: "AI Agents" },
    ],
  },

  "ai-chatbot-development": {
    eyebrow: "AI Chatbot Development",
    title: "Chatbots customers don't immediately ask for a human.",
    lede: "Production AI chatbots and voice assistants — grounded in your knowledge, integrated with your systems, and built to actually deflect tickets.",
    accent: "var(--brand-green)",
    Icon: MessageSquareCode,
    heroStats: [
      { value: "30+", label: "Chatbots in prod" },
      { value: "62%", label: "Avg. deflection" },
      { value: "92%", label: "Answer acceptance" },
      { value: "8 langs", label: "Multilingual ready" },
    ],
    whoFor: [
      "Customer support orgs drowning in repetitive tier-1 tickets.",
      "Sales teams needing always-on lead qualification across web, WhatsApp, and IVR.",
      "Internal IT/HR teams handling thousands of FAQ-style requests weekly.",
      "Companies whose 2019-era rule-based bots are embarrassing them on social media.",
    ],
    capabilities: [
      { title: "Conversational design", body: "Tone, fallback strategy, escalation logic, and persona — designed before a model is wired up." },
      { title: "Knowledge grounding", body: "RAG over your docs, ticket history, and product catalog — with citations and confidence scoring." },
      { title: "System integrations", body: "Salesforce, Zendesk, ServiceNow, Stripe, custom APIs — actions, not just answers." },
      { title: "Voice & multilingual", body: "Voice via Twilio/Vonage, multilingual via Whisper and translation pipelines tuned per locale." },
      { title: "Evals & safety", body: "Domain-specific eval suites, red-team harnesses, PII redaction, and policy filters." },
      { title: "Analytics & ops", body: "Conversation analytics, intent drift detection, and weekly fine-tuning loops." },
    ],
    outcomes: [
      { metric: "62%", label: "Ticket deflection", context: "Customer support bot for a D2C brand — measured against pre-launch baseline." },
      { metric: "37%", label: "AHT reduction", context: "Agent-assist deployment at a top-5 Indian bank — full citations on every response." },
      { metric: "4.6/5", label: "End-user CSAT", context: "Across a 12-month rolling window post-launch on a logistics support bot." },
    ],
    process: [
      { title: "Scope", body: "Top 50 intents by volume, knowledge sources, integrations, and a measurable deflection target." },
      { title: "Build", body: "Knowledge pipeline, RAG, integrations, eval harness, and a staging cohort." },
      { title: "Launch", body: "Phased rollout with human-in-the-loop fallback and per-intent kill switches." },
      { title: "Improve", body: "Weekly conversation review, intent gap analysis, and continuous fine-tuning." },
    ],
    tech: ["OpenAI", "Anthropic", "LangChain", "LlamaIndex", "Twilio", "Vonage", "Whisper", "Pinecone", "Weaviate"],
    faqs: [
      { q: "How do you prevent hallucinations?", a: "Strict grounding, citation requirements, confidence thresholds, and graceful 'I don't know' fallbacks." },
      { q: "Can it handle our regulated industry?", a: "Yes — we ship into BFSI and healthcare with full PII redaction, audit logs, and policy filters." },
      { q: "What's the typical timeline?", a: "8–12 weeks to a deflecting v1 for a focused scope. Faster with a clean knowledge base." },
    ],
    siblingLinks: [
      { to: "/services/ai-solutions", label: "AI Solutions" },
      { to: "/services/ai-agents-development", label: "AI Agents" },
      { to: "/services/generative-ai-development", label: "Generative AI" },
    ],
  },

  "generative-ai-development": {
    eyebrow: "Generative AI Development",
    title: "Generative AI products that earn their keep.",
    lede: "Generative AI tools, copilots, and content systems — built for real workflows, with the evals, guardrails, and economics to ship to production.",
    accent: "var(--brand-orange)",
    Icon: Brain,
    heroStats: [
      { value: "20+", label: "GenAI products" },
      { value: "98.6%", label: "Eval pass rate" },
      { value: "60%", label: "Cost vs. naive RAG" },
      { value: "Multi-modal", label: "By default" },
    ],
    whoFor: [
      "Product teams building AI copilots inside existing SaaS products.",
      "Content and marketing orgs scaling output without losing brand voice.",
      "Internal tool teams shipping generative workflows for ops, legal, HR.",
      "Enterprises needing fully governed GenAI inside their VPC.",
    ],
    capabilities: [
      { title: "Text generation systems", body: "Copilots, drafting tools, summarizers, and rewriters — tuned to your tone and policies." },
      { title: "Image & vision systems", body: "Generation, editing, OCR, and visual understanding — including diffusion fine-tuning where relevant." },
      { title: "Code generation", body: "Code copilots for internal codebases — fine-tuned on your conventions and architecture." },
      { title: "Multi-modal pipelines", body: "Text + image + audio fused into workflows like document understanding and inspection automation." },
      { title: "Eval & safety", body: "Brand voice evals, factuality evals, bias testing, and red-team coverage tuned per use case." },
      { title: "Cost engineering", body: "Smart routing, prompt caching, model cascading, and per-feature spend budgets." },
    ],
    outcomes: [
      { metric: "4.7/5", label: "User NPS", context: "Generative drafting tool inside a B2B SaaS — measured at 30-day usage." },
      { metric: "60%", label: "Cost reduction", context: "Vs. naive single-model RAG, via smart routing and prompt caching." },
      { metric: "11×", label: "Faster workflows", context: "Document review pipeline using multi-modal extraction + LLM summarization." },
    ],
    process: [
      { title: "Define", body: "Use case, success metric, eval set, brand voice constraints, and acceptable cost-per-request." },
      { title: "Build", body: "Model selection, prompts, retrieval, guardrails, and eval harness — versioned in CI." },
      { title: "Harden", body: "Cost ceilings, fallbacks, content moderation, and progressive rollout via feature flags." },
      { title: "Operate", body: "Observability, drift detection, weekly model and prompt improvement cycles." },
    ],
    tech: ["OpenAI", "Anthropic", "Llama", "Stable Diffusion", "Whisper", "vLLM", "LangChain", "Modal", "Replicate"],
    faqs: [
      { q: "Can it be on-prem?", a: "Yes — many engagements use open-weight models running in your VPC or on-prem GPUs." },
      { q: "How do you handle IP and licensing?", a: "We track model and dataset licenses and only ship into commercial use cases with clean provenance." },
      { q: "What about copyright risk on outputs?", a: "We layer model choice, prompt patterns, and output filters to minimize regurgitation risk." },
    ],
    siblingLinks: [
      { to: "/services/ai-solutions", label: "AI Solutions" },
      { to: "/services/custom-ai-development", label: "Custom AI Development" },
      { to: "/services/ai-agents-development", label: "AI Agents" },
    ],
  },

  "ai-agents-development": {
    eyebrow: "AI Agents Development",
    title: "Agentic AI that does the work — not just describes it.",
    lede: "Multi-step AI agents that plan, call tools, and complete real workflows — with the evals, observability, and human-in-the-loop controls to deploy them safely.",
    accent: "var(--brand-red)",
    Icon: Bot,
    heroStats: [
      { value: "15+", label: "Agentic systems shipped" },
      { value: "8 steps", label: "Avg. plan depth" },
      { value: "100%", label: "Action audit trail" },
      { value: "HITL", label: "Default safety net" },
    ],
    whoFor: [
      "Ops teams whose work is multi-step and tool-heavy but rules-based at the edges.",
      "Engineering teams building agentic features inside existing products.",
      "Companies replacing fragile RPA workflows with reasoning-driven automation.",
      "Research teams pushing toward genuinely autonomous workflows with audit trails.",
    ],
    capabilities: [
      { title: "Agent architecture", body: "Single-agent, multi-agent, and supervisor patterns chosen per workflow shape." },
      { title: "Tool & API integration", body: "Function calling, MCP, retrieval, and side-effect-safe wrappers around your APIs." },
      { title: "Memory & state", body: "Short and long-term memory designs that don't blow up tokens or accuracy." },
      { title: "Evals for agents", body: "Trajectory evals, step-level evals, outcome evals — measuring more than just the final answer." },
      { title: "Guardrails & HITL", body: "Policy enforcement, blast-radius limits, and human approval steps for risky actions." },
      { title: "Observability", body: "Full trace of every plan, tool call, and reasoning step — searchable and replayable." },
    ],
    outcomes: [
      { metric: "73%", label: "Workflow automation", context: "Procurement workflow agent at a manufacturing client — humans approve, agent executes." },
      { metric: "100%", label: "Auditable actions", context: "Every tool call signed, logged, and replayable — meets internal audit and SOC requirements." },
      { metric: "8 steps", label: "Avg. plan depth", context: "Real production agents handling complex multi-system workflows in BFSI and logistics." },
    ],
    process: [
      { title: "Map the workflow", body: "Decompose the workflow, identify decision points, and define safe vs. risky actions." },
      { title: "Build the agent", body: "Tools, prompts, memory, planner, and policy layer — wired together with observability from day one." },
      { title: "Eval & harden", body: "Trajectory evals, failure-mode testing, blast-radius limits, and HITL approval flows." },
      { title: "Deploy & monitor", body: "Phased rollout, per-action kill switches, and weekly trajectory reviews." },
    ],
    tech: ["LangGraph", "OpenAI", "Anthropic", "MCP", "Temporal", "LiteLLM", "Arize", "Langfuse"],
    faqs: [
      { q: "Are agents production-ready?", a: "For well-scoped workflows with HITL — yes. We don't pretend they're ready for unsupervised autonomy yet." },
      { q: "How do you control blast radius?", a: "Policy layers, scoped credentials, action allowlists, and mandatory human approval on irreversible actions." },
      { q: "Can agents call our internal systems?", a: "Yes — via signed, audited, scoped wrappers. We never give an agent broad IAM permissions." },
    ],
    siblingLinks: [
      { to: "/services/ai-solutions", label: "AI Solutions" },
      { to: "/services/custom-ai-development", label: "Custom AI Development" },
      { to: "/services/ai-integration", label: "AI Integration" },
    ],
  },

  "ai-integration": {
    eyebrow: "AI Integration",
    title: "AI that snaps into the systems you already run.",
    lede: "Integrate AI into Salesforce, SAP, ServiceNow, custom apps, and the messy middleware no one wants to talk about — without rebuilding the rest of your stack.",
    accent: "var(--brand-orange)",
    Icon: Plug,
    heroStats: [
      { value: "80+", label: "AI integrations shipped" },
      { value: "20+", label: "Enterprise systems" },
      { value: "100%", label: "Audit-traceable" },
      { value: "Iso-VPC", label: "Where required" },
    ],
    whoFor: [
      "Enterprise IT teams wiring AI features into Salesforce, SAP, ServiceNow, or Workday.",
      "Product teams adding AI features to existing SaaS products without rebuilding the front-end.",
      "Companies whose AI vendors keep failing to integrate cleanly with legacy systems.",
      "BFSI and healthcare orgs that need every AI call audited, logged, and reversible.",
    ],
    capabilities: [
      { title: "Enterprise system integration", body: "Salesforce, SAP, ServiceNow, Workday, Oracle, Microsoft 365 — APEX, RFC, OData, REST, GraphQL." },
      { title: "Middleware & iPaaS", body: "MuleSoft, Boomi, Workato, and custom event buses — used or replaced, depending on the situation." },
      { title: "AI gateways", body: "Single ingress for all AI traffic — model routing, cost ceilings, rate limits, and audit logging." },
      { title: "Identity & access", body: "OAuth, SAML, SCIM, ABAC — AI calls scoped to the calling user's actual permissions." },
      { title: "Observability & audit", body: "Per-call logging with payload redaction, lineage, and full replay — designed for regulated audits." },
      { title: "Vendor model brokering", body: "OpenAI, Anthropic, Google, Azure OpenAI, Cohere, in-VPC open models — with failover and cost optimization." },
    ],
    outcomes: [
      { metric: "11 wks", label: "Avg. integration", context: "From design to a production integration across 3 enterprise systems." },
      { metric: "100%", label: "Audit-traceable calls", context: "Default across BFSI and healthcare engagements — meets internal and external audit." },
      { metric: "32%", label: "AI spend reduction", context: "Via routing, caching, and per-feature cost ceilings on a centralized AI gateway." },
    ],
    process: [
      { title: "Inventory", body: "Map systems, integration patterns, identity model, and audit requirements." },
      { title: "Design", body: "Gateway architecture, integration contracts, security posture, and observability plan." },
      { title: "Build", body: "Integrations, gateway, observability, and per-feature kill switches." },
      { title: "Operate", body: "Cost, latency, and accuracy monitoring with quarterly architectural reviews." },
    ],
    tech: ["Salesforce", "SAP", "ServiceNow", "Workday", "MuleSoft", "Workato", "LiteLLM", "Kong", "Apigee"],
    faqs: [
      { q: "Can you work with our SaaS vendors directly?", a: "Yes — we routinely co-engineer integrations alongside vendor success and engineering teams." },
      { q: "Do you handle change management?", a: "We partner with your change management function — and bring playbooks from past rollouts." },
      { q: "How do you keep AI costs predictable?", a: "Centralized gateway, per-feature budgets, and weekly cost reviews — not 'we'll see what the bill says'." },
    ],
    siblingLinks: [
      { to: "/services/ai-solutions", label: "AI Solutions" },
      { to: "/services/ai-agents-development", label: "AI Agents" },
      { to: "/services/cloud-infrastructure", label: "Cloud & Infrastructure" },
    ],
  },
};

export const subServiceSlugs = Object.keys(subServices);

export const subServiceIcons: Record<string, LucideIcon> = Object.fromEntries(
  Object.entries(subServices).map(([k, v]) => [k, v.Icon]),
);
