/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeamRouteImport } from './routes/team'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as MissionVisionRouteImport } from './routes/mission-vision'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CaseStudiesRouteImport } from './routes/case-studies'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AwardsAchievementsRouteImport } from './routes/awards-achievements'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as CareersIndexRouteImport } from './routes/careers.index'
import { Route as ServicesWebApplicationDevelopmentRouteImport } from './routes/services.web-application-development'
import { Route as ServicesSoftwareDevelopmentRouteImport } from './routes/services.software-development'
import { Route as ServicesProductEngineeringRouteImport } from './routes/services.product-engineering'
import { Route as ServicesOffshoreDevelopmentRouteImport } from './routes/services.offshore-development'
import { Route as ServicesMobileAppDevelopmentRouteImport } from './routes/services.mobile-app-development'
import { Route as ServicesItStaffingRouteImport } from './routes/services.it-staffing'
import { Route as ServicesItOutsourcingRouteImport } from './routes/services.it-outsourcing'
import { Route as ServicesGlobalCapabilityCenterRouteImport } from './routes/services.global-capability-center'
import { Route as ServicesGenerativeAiDevelopmentRouteImport } from './routes/services.generative-ai-development'
import { Route as ServicesFrontEndDevelopmentRouteImport } from './routes/services.front-end-development'
import { Route as ServicesDataEngineeringRouteImport } from './routes/services.data-engineering'
import { Route as ServicesCybersecurityRouteImport } from './routes/services.cybersecurity'
import { Route as ServicesCustomAiDevelopmentRouteImport } from './routes/services.custom-ai-development'
import { Route as ServicesCloudInfrastructureRouteImport } from './routes/services.cloud-infrastructure'
import { Route as ServicesCloudComputingRouteImport } from './routes/services.cloud-computing'
import { Route as ServicesAiSolutionsRouteImport } from './routes/services.ai-solutions'
import { Route as ServicesAiIntegrationRouteImport } from './routes/services.ai-integration'
import { Route as ServicesAiChatbotDevelopmentRouteImport } from './routes/services.ai-chatbot-development'
import { Route as ServicesAiAgentsDevelopmentRouteImport } from './routes/services.ai-agents-development'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as HireWindsurfAiDevelopersRouteImport } from './routes/hire.windsurf-ai-developers'
import { Route as HireWebAppDeveloperRouteImport } from './routes/hire.web-app-developer'
import { Route as HireSoftwareDeveloperRouteImport } from './routes/hire.software-developer'
import { Route as HireReplitAiDevelopersRouteImport } from './routes/hire.replit-ai-developers'
import { Route as HirePromptEngineerRouteImport } from './routes/hire.prompt-engineer'
import { Route as HireOpenaiDevelopersRouteImport } from './routes/hire.openai-developers'
import { Route as HireMobileAppDeveloperRouteImport } from './routes/hire.mobile-app-developer'
import { Route as HireLovableAiDevelopersRouteImport } from './routes/hire.lovable-ai-developers'
import { Route as HireGoogleAntigravityDevelopersRouteImport } from './routes/hire.google-antigravity-developers'
import { Route as HireGenerativeAiDevelopersRouteImport } from './routes/hire.generative-ai-developers'
import { Route as HireGeminiDevelopersRouteImport } from './routes/hire.gemini-developers'
import { Route as HireFullstackDevelopersRouteImport } from './routes/hire.fullstack-developers'
import { Route as HireFrontendDevelopersRouteImport } from './routes/hire.frontend-developers'
import { Route as HireDevopsDevelopersRouteImport } from './routes/hire.devops-developers'
import { Route as HireCursorAiDevelopersRouteImport } from './routes/hire.cursor-ai-developers'
import { Route as HireChatgptDevelopersRouteImport } from './routes/hire.chatgpt-developers'
import { Route as HireChatbotDevelopersRouteImport } from './routes/hire.chatbot-developers'
import { Route as HireBoltNewAiDevelopersRouteImport } from './routes/hire.bolt-new-ai-developers'
import { Route as HireBackendDevelopersRouteImport } from './routes/hire.backend-developers'
import { Route as HireAndroidDevelopersRouteImport } from './routes/hire.android-developers'
import { Route as HireAiDevelopersRouteImport } from './routes/hire.ai-developers'
import { Route as HireSlugRouteImport } from './routes/hire.$slug'
import { Route as CaseStudiesSlugRouteImport } from './routes/case-studies/$slug'
import { Route as CareersLifeAtPureTechnologyRouteImport } from './routes/careers.life-at-pure-technology'
import { Route as CareersBenefitsPerksRouteImport } from './routes/careers.benefits-perks'

const TeamRoute = TeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionVisionRoute = MissionVisionRouteImport.update({
  id: '/mission-vision',
  path: '/mission-vision',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesRoute = CaseStudiesRouteImport.update({
  id: '/case-studies',
  path: '/case-studies',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AwardsAchievementsRoute = AwardsAchievementsRouteImport.update({
  id: '/awards-achievements',
  path: '/awards-achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const CareersIndexRoute = CareersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CareersRoute,
} as any)
const ServicesWebApplicationDevelopmentRoute =
  ServicesWebApplicationDevelopmentRouteImport.update({
    id: '/web-application-development',
    path: '/web-application-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesSoftwareDevelopmentRoute =
  ServicesSoftwareDevelopmentRouteImport.update({
    id: '/software-development',
    path: '/software-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesProductEngineeringRoute =
  ServicesProductEngineeringRouteImport.update({
    id: '/product-engineering',
    path: '/product-engineering',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesOffshoreDevelopmentRoute =
  ServicesOffshoreDevelopmentRouteImport.update({
    id: '/offshore-development',
    path: '/offshore-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesMobileAppDevelopmentRoute =
  ServicesMobileAppDevelopmentRouteImport.update({
    id: '/mobile-app-development',
    path: '/mobile-app-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesItStaffingRoute = ServicesItStaffingRouteImport.update({
  id: '/it-staffing',
  path: '/it-staffing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesItOutsourcingRoute = ServicesItOutsourcingRouteImport.update({
  id: '/it-outsourcing',
  path: '/it-outsourcing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesGlobalCapabilityCenterRoute =
  ServicesGlobalCapabilityCenterRouteImport.update({
    id: '/global-capability-center',
    path: '/global-capability-center',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesGenerativeAiDevelopmentRoute =
  ServicesGenerativeAiDevelopmentRouteImport.update({
    id: '/generative-ai-development',
    path: '/generative-ai-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesFrontEndDevelopmentRoute =
  ServicesFrontEndDevelopmentRouteImport.update({
    id: '/front-end-development',
    path: '/front-end-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesDataEngineeringRoute = ServicesDataEngineeringRouteImport.update({
  id: '/data-engineering',
  path: '/data-engineering',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCybersecurityRoute = ServicesCybersecurityRouteImport.update({
  id: '/cybersecurity',
  path: '/cybersecurity',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCustomAiDevelopmentRoute =
  ServicesCustomAiDevelopmentRouteImport.update({
    id: '/custom-ai-development',
    path: '/custom-ai-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesCloudInfrastructureRoute =
  ServicesCloudInfrastructureRouteImport.update({
    id: '/cloud-infrastructure',
    path: '/cloud-infrastructure',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesCloudComputingRoute = ServicesCloudComputingRouteImport.update({
  id: '/cloud-computing',
  path: '/cloud-computing',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAiSolutionsRoute = ServicesAiSolutionsRouteImport.update({
  id: '/ai-solutions',
  path: '/ai-solutions',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAiIntegrationRoute = ServicesAiIntegrationRouteImport.update({
  id: '/ai-integration',
  path: '/ai-integration',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAiChatbotDevelopmentRoute =
  ServicesAiChatbotDevelopmentRouteImport.update({
    id: '/ai-chatbot-development',
    path: '/ai-chatbot-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesAiAgentsDevelopmentRoute =
  ServicesAiAgentsDevelopmentRouteImport.update({
    id: '/ai-agents-development',
    path: '/ai-agents-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const HireWindsurfAiDevelopersRoute =
  HireWindsurfAiDevelopersRouteImport.update({
    id: '/hire/windsurf-ai-developers',
    path: '/hire/windsurf-ai-developers',
    getParentRoute: () => rootRouteImport,
  } as any)
const HireWebAppDeveloperRoute = HireWebAppDeveloperRouteImport.update({
  id: '/hire/web-app-developer',
  path: '/hire/web-app-developer',
  getParentRoute: () => rootRouteImport,
} as any)
const HireSoftwareDeveloperRoute = HireSoftwareDeveloperRouteImport.update({
  id: '/hire/software-developer',
  path: '/hire/software-developer',
  getParentRoute: () => rootRouteImport,
} as any)
const HireReplitAiDevelopersRoute = HireReplitAiDevelopersRouteImport.update({
  id: '/hire/replit-ai-developers',
  path: '/hire/replit-ai-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HirePromptEngineerRoute = HirePromptEngineerRouteImport.update({
  id: '/hire/prompt-engineer',
  path: '/hire/prompt-engineer',
  getParentRoute: () => rootRouteImport,
} as any)
const HireOpenaiDevelopersRoute = HireOpenaiDevelopersRouteImport.update({
  id: '/hire/openai-developers',
  path: '/hire/openai-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HireMobileAppDeveloperRoute = HireMobileAppDeveloperRouteImport.update({
  id: '/hire/mobile-app-developer',
  path: '/hire/mobile-app-developer',
  getParentRoute: () => rootRouteImport,
} as any)
const HireLovableAiDevelopersRoute = HireLovableAiDevelopersRouteImport.update({
  id: '/hire/lovable-ai-developers',
  path: '/hire/lovable-ai-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HireGoogleAntigravityDevelopersRoute =
  HireGoogleAntigravityDevelopersRouteImport.update({
    id: '/hire/google-antigravity-developers',
    path: '/hire/google-antigravity-developers',
    getParentRoute: () => rootRouteImport,
  } as any)
const HireGenerativeAiDevelopersRoute =
  HireGenerativeAiDevelopersRouteImport.update({
    id: '/hire/generative-ai-developers',
    path: '/hire/generative-ai-developers',
    getParentRoute: () => rootRouteImport,
  } as any)
const HireGeminiDevelopersRoute = HireGeminiDevelopersRouteImport.update({
  id: '/hire/gemini-developers',
  path: '/hire/gemini-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HireFullstackDevelopersRoute = HireFullstackDevelopersRouteImport.update({
  id: '/hire/fullstack-developers',
  path: '/hire/fullstack-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HireFrontendDevelopersRoute = HireFrontendDevelopersRouteImport.update({
  id: '/hire/frontend-developers',
  path: '/hire/frontend-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HireDevopsDevelopersRoute = HireDevopsDevelopersRouteImport.update({
  id: '/hire/devops-developers',
  path: '/hire/devops-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HireCursorAiDevelopersRoute = HireCursorAiDevelopersRouteImport.update({
  id: '/hire/cursor-ai-developers',
  path: '/hire/cursor-ai-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HireChatgptDevelopersRoute = HireChatgptDevelopersRouteImport.update({
  id: '/hire/chatgpt-developers',
  path: '/hire/chatgpt-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HireChatbotDevelopersRoute = HireChatbotDevelopersRouteImport.update({
  id: '/hire/chatbot-developers',
  path: '/hire/chatbot-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HireBoltNewAiDevelopersRoute = HireBoltNewAiDevelopersRouteImport.update({
  id: '/hire/bolt-new-ai-developers',
  path: '/hire/bolt-new-ai-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HireBackendDevelopersRoute = HireBackendDevelopersRouteImport.update({
  id: '/hire/backend-developers',
  path: '/hire/backend-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HireAndroidDevelopersRoute = HireAndroidDevelopersRouteImport.update({
  id: '/hire/android-developers',
  path: '/hire/android-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HireAiDevelopersRoute = HireAiDevelopersRouteImport.update({
  id: '/hire/ai-developers',
  path: '/hire/ai-developers',
  getParentRoute: () => rootRouteImport,
} as any)
const HireSlugRoute = HireSlugRouteImport.update({
  id: '/hire/$slug',
  path: '/hire/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CaseStudiesSlugRoute = CaseStudiesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => CaseStudiesRoute,
} as any)
const CareersLifeAtPureTechnologyRoute =
  CareersLifeAtPureTechnologyRouteImport.update({
    id: '/life-at-pure-technology',
    path: '/life-at-pure-technology',
    getParentRoute: () => CareersRoute,
  } as any)
const CareersBenefitsPerksRoute = CareersBenefitsPerksRouteImport.update({
  id: '/benefits-perks',
  path: '/benefits-perks',
  getParentRoute: () => CareersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/awards-achievements': typeof AwardsAchievementsRoute
  '/careers': typeof CareersRouteWithChildren
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/mission-vision': typeof MissionVisionRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/careers/benefits-perks': typeof CareersBenefitsPerksRoute
  '/careers/life-at-pure-technology': typeof CareersLifeAtPureTechnologyRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/hire/$slug': typeof HireSlugRoute
  '/hire/ai-developers': typeof HireAiDevelopersRoute
  '/hire/android-developers': typeof HireAndroidDevelopersRoute
  '/hire/backend-developers': typeof HireBackendDevelopersRoute
  '/hire/bolt-new-ai-developers': typeof HireBoltNewAiDevelopersRoute
  '/hire/chatbot-developers': typeof HireChatbotDevelopersRoute
  '/hire/chatgpt-developers': typeof HireChatgptDevelopersRoute
  '/hire/cursor-ai-developers': typeof HireCursorAiDevelopersRoute
  '/hire/devops-developers': typeof HireDevopsDevelopersRoute
  '/hire/frontend-developers': typeof HireFrontendDevelopersRoute
  '/hire/fullstack-developers': typeof HireFullstackDevelopersRoute
  '/hire/gemini-developers': typeof HireGeminiDevelopersRoute
  '/hire/generative-ai-developers': typeof HireGenerativeAiDevelopersRoute
  '/hire/google-antigravity-developers': typeof HireGoogleAntigravityDevelopersRoute
  '/hire/lovable-ai-developers': typeof HireLovableAiDevelopersRoute
  '/hire/mobile-app-developer': typeof HireMobileAppDeveloperRoute
  '/hire/openai-developers': typeof HireOpenaiDevelopersRoute
  '/hire/prompt-engineer': typeof HirePromptEngineerRoute
  '/hire/replit-ai-developers': typeof HireReplitAiDevelopersRoute
  '/hire/software-developer': typeof HireSoftwareDeveloperRoute
  '/hire/web-app-developer': typeof HireWebAppDeveloperRoute
  '/hire/windsurf-ai-developers': typeof HireWindsurfAiDevelopersRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/ai-agents-development': typeof ServicesAiAgentsDevelopmentRoute
  '/services/ai-chatbot-development': typeof ServicesAiChatbotDevelopmentRoute
  '/services/ai-integration': typeof ServicesAiIntegrationRoute
  '/services/ai-solutions': typeof ServicesAiSolutionsRoute
  '/services/cloud-computing': typeof ServicesCloudComputingRoute
  '/services/cloud-infrastructure': typeof ServicesCloudInfrastructureRoute
  '/services/custom-ai-development': typeof ServicesCustomAiDevelopmentRoute
  '/services/cybersecurity': typeof ServicesCybersecurityRoute
  '/services/data-engineering': typeof ServicesDataEngineeringRoute
  '/services/front-end-development': typeof ServicesFrontEndDevelopmentRoute
  '/services/generative-ai-development': typeof ServicesGenerativeAiDevelopmentRoute
  '/services/global-capability-center': typeof ServicesGlobalCapabilityCenterRoute
  '/services/it-outsourcing': typeof ServicesItOutsourcingRoute
  '/services/it-staffing': typeof ServicesItStaffingRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
  '/services/offshore-development': typeof ServicesOffshoreDevelopmentRoute
  '/services/product-engineering': typeof ServicesProductEngineeringRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
  '/services/web-application-development': typeof ServicesWebApplicationDevelopmentRoute
  '/careers/': typeof CareersIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/awards-achievements': typeof AwardsAchievementsRoute
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/mission-vision': typeof MissionVisionRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/careers/benefits-perks': typeof CareersBenefitsPerksRoute
  '/careers/life-at-pure-technology': typeof CareersLifeAtPureTechnologyRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/hire/$slug': typeof HireSlugRoute
  '/hire/ai-developers': typeof HireAiDevelopersRoute
  '/hire/android-developers': typeof HireAndroidDevelopersRoute
  '/hire/backend-developers': typeof HireBackendDevelopersRoute
  '/hire/bolt-new-ai-developers': typeof HireBoltNewAiDevelopersRoute
  '/hire/chatbot-developers': typeof HireChatbotDevelopersRoute
  '/hire/chatgpt-developers': typeof HireChatgptDevelopersRoute
  '/hire/cursor-ai-developers': typeof HireCursorAiDevelopersRoute
  '/hire/devops-developers': typeof HireDevopsDevelopersRoute
  '/hire/frontend-developers': typeof HireFrontendDevelopersRoute
  '/hire/fullstack-developers': typeof HireFullstackDevelopersRoute
  '/hire/gemini-developers': typeof HireGeminiDevelopersRoute
  '/hire/generative-ai-developers': typeof HireGenerativeAiDevelopersRoute
  '/hire/google-antigravity-developers': typeof HireGoogleAntigravityDevelopersRoute
  '/hire/lovable-ai-developers': typeof HireLovableAiDevelopersRoute
  '/hire/mobile-app-developer': typeof HireMobileAppDeveloperRoute
  '/hire/openai-developers': typeof HireOpenaiDevelopersRoute
  '/hire/prompt-engineer': typeof HirePromptEngineerRoute
  '/hire/replit-ai-developers': typeof HireReplitAiDevelopersRoute
  '/hire/software-developer': typeof HireSoftwareDeveloperRoute
  '/hire/web-app-developer': typeof HireWebAppDeveloperRoute
  '/hire/windsurf-ai-developers': typeof HireWindsurfAiDevelopersRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/ai-agents-development': typeof ServicesAiAgentsDevelopmentRoute
  '/services/ai-chatbot-development': typeof ServicesAiChatbotDevelopmentRoute
  '/services/ai-integration': typeof ServicesAiIntegrationRoute
  '/services/ai-solutions': typeof ServicesAiSolutionsRoute
  '/services/cloud-computing': typeof ServicesCloudComputingRoute
  '/services/cloud-infrastructure': typeof ServicesCloudInfrastructureRoute
  '/services/custom-ai-development': typeof ServicesCustomAiDevelopmentRoute
  '/services/cybersecurity': typeof ServicesCybersecurityRoute
  '/services/data-engineering': typeof ServicesDataEngineeringRoute
  '/services/front-end-development': typeof ServicesFrontEndDevelopmentRoute
  '/services/generative-ai-development': typeof ServicesGenerativeAiDevelopmentRoute
  '/services/global-capability-center': typeof ServicesGlobalCapabilityCenterRoute
  '/services/it-outsourcing': typeof ServicesItOutsourcingRoute
  '/services/it-staffing': typeof ServicesItStaffingRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
  '/services/offshore-development': typeof ServicesOffshoreDevelopmentRoute
  '/services/product-engineering': typeof ServicesProductEngineeringRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
  '/services/web-application-development': typeof ServicesWebApplicationDevelopmentRoute
  '/careers': typeof CareersIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/awards-achievements': typeof AwardsAchievementsRoute
  '/careers': typeof CareersRouteWithChildren
  '/case-studies': typeof CaseStudiesRouteWithChildren
  '/contact': typeof ContactRoute
  '/gallery': typeof GalleryRoute
  '/mission-vision': typeof MissionVisionRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/team': typeof TeamRoute
  '/careers/benefits-perks': typeof CareersBenefitsPerksRoute
  '/careers/life-at-pure-technology': typeof CareersLifeAtPureTechnologyRoute
  '/case-studies/$slug': typeof CaseStudiesSlugRoute
  '/hire/$slug': typeof HireSlugRoute
  '/hire/ai-developers': typeof HireAiDevelopersRoute
  '/hire/android-developers': typeof HireAndroidDevelopersRoute
  '/hire/backend-developers': typeof HireBackendDevelopersRoute
  '/hire/bolt-new-ai-developers': typeof HireBoltNewAiDevelopersRoute
  '/hire/chatbot-developers': typeof HireChatbotDevelopersRoute
  '/hire/chatgpt-developers': typeof HireChatgptDevelopersRoute
  '/hire/cursor-ai-developers': typeof HireCursorAiDevelopersRoute
  '/hire/devops-developers': typeof HireDevopsDevelopersRoute
  '/hire/frontend-developers': typeof HireFrontendDevelopersRoute
  '/hire/fullstack-developers': typeof HireFullstackDevelopersRoute
  '/hire/gemini-developers': typeof HireGeminiDevelopersRoute
  '/hire/generative-ai-developers': typeof HireGenerativeAiDevelopersRoute
  '/hire/google-antigravity-developers': typeof HireGoogleAntigravityDevelopersRoute
  '/hire/lovable-ai-developers': typeof HireLovableAiDevelopersRoute
  '/hire/mobile-app-developer': typeof HireMobileAppDeveloperRoute
  '/hire/openai-developers': typeof HireOpenaiDevelopersRoute
  '/hire/prompt-engineer': typeof HirePromptEngineerRoute
  '/hire/replit-ai-developers': typeof HireReplitAiDevelopersRoute
  '/hire/software-developer': typeof HireSoftwareDeveloperRoute
  '/hire/web-app-developer': typeof HireWebAppDeveloperRoute
  '/hire/windsurf-ai-developers': typeof HireWindsurfAiDevelopersRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/ai-agents-development': typeof ServicesAiAgentsDevelopmentRoute
  '/services/ai-chatbot-development': typeof ServicesAiChatbotDevelopmentRoute
  '/services/ai-integration': typeof ServicesAiIntegrationRoute
  '/services/ai-solutions': typeof ServicesAiSolutionsRoute
  '/services/cloud-computing': typeof ServicesCloudComputingRoute
  '/services/cloud-infrastructure': typeof ServicesCloudInfrastructureRoute
  '/services/custom-ai-development': typeof ServicesCustomAiDevelopmentRoute
  '/services/cybersecurity': typeof ServicesCybersecurityRoute
  '/services/data-engineering': typeof ServicesDataEngineeringRoute
  '/services/front-end-development': typeof ServicesFrontEndDevelopmentRoute
  '/services/generative-ai-development': typeof ServicesGenerativeAiDevelopmentRoute
  '/services/global-capability-center': typeof ServicesGlobalCapabilityCenterRoute
  '/services/it-outsourcing': typeof ServicesItOutsourcingRoute
  '/services/it-staffing': typeof ServicesItStaffingRoute
  '/services/mobile-app-development': typeof ServicesMobileAppDevelopmentRoute
  '/services/offshore-development': typeof ServicesOffshoreDevelopmentRoute
  '/services/product-engineering': typeof ServicesProductEngineeringRoute
  '/services/software-development': typeof ServicesSoftwareDevelopmentRoute
  '/services/web-application-development': typeof ServicesWebApplicationDevelopmentRoute
  '/careers/': typeof CareersIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/awards-achievements'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/gallery'
    | '/mission-vision'
    | '/services'
    | '/sitemap.xml'
    | '/team'
    | '/careers/benefits-perks'
    | '/careers/life-at-pure-technology'
    | '/case-studies/$slug'
    | '/hire/$slug'
    | '/hire/ai-developers'
    | '/hire/android-developers'
    | '/hire/backend-developers'
    | '/hire/bolt-new-ai-developers'
    | '/hire/chatbot-developers'
    | '/hire/chatgpt-developers'
    | '/hire/cursor-ai-developers'
    | '/hire/devops-developers'
    | '/hire/frontend-developers'
    | '/hire/fullstack-developers'
    | '/hire/gemini-developers'
    | '/hire/generative-ai-developers'
    | '/hire/google-antigravity-developers'
    | '/hire/lovable-ai-developers'
    | '/hire/mobile-app-developer'
    | '/hire/openai-developers'
    | '/hire/prompt-engineer'
    | '/hire/replit-ai-developers'
    | '/hire/software-developer'
    | '/hire/web-app-developer'
    | '/hire/windsurf-ai-developers'
    | '/services/$slug'
    | '/services/ai-agents-development'
    | '/services/ai-chatbot-development'
    | '/services/ai-integration'
    | '/services/ai-solutions'
    | '/services/cloud-computing'
    | '/services/cloud-infrastructure'
    | '/services/custom-ai-development'
    | '/services/cybersecurity'
    | '/services/data-engineering'
    | '/services/front-end-development'
    | '/services/generative-ai-development'
    | '/services/global-capability-center'
    | '/services/it-outsourcing'
    | '/services/it-staffing'
    | '/services/mobile-app-development'
    | '/services/offshore-development'
    | '/services/product-engineering'
    | '/services/software-development'
    | '/services/web-application-development'
    | '/careers/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/awards-achievements'
    | '/case-studies'
    | '/contact'
    | '/gallery'
    | '/mission-vision'
    | '/sitemap.xml'
    | '/team'
    | '/careers/benefits-perks'
    | '/careers/life-at-pure-technology'
    | '/case-studies/$slug'
    | '/hire/$slug'
    | '/hire/ai-developers'
    | '/hire/android-developers'
    | '/hire/backend-developers'
    | '/hire/bolt-new-ai-developers'
    | '/hire/chatbot-developers'
    | '/hire/chatgpt-developers'
    | '/hire/cursor-ai-developers'
    | '/hire/devops-developers'
    | '/hire/frontend-developers'
    | '/hire/fullstack-developers'
    | '/hire/gemini-developers'
    | '/hire/generative-ai-developers'
    | '/hire/google-antigravity-developers'
    | '/hire/lovable-ai-developers'
    | '/hire/mobile-app-developer'
    | '/hire/openai-developers'
    | '/hire/prompt-engineer'
    | '/hire/replit-ai-developers'
    | '/hire/software-developer'
    | '/hire/web-app-developer'
    | '/hire/windsurf-ai-developers'
    | '/services/$slug'
    | '/services/ai-agents-development'
    | '/services/ai-chatbot-development'
    | '/services/ai-integration'
    | '/services/ai-solutions'
    | '/services/cloud-computing'
    | '/services/cloud-infrastructure'
    | '/services/custom-ai-development'
    | '/services/cybersecurity'
    | '/services/data-engineering'
    | '/services/front-end-development'
    | '/services/generative-ai-development'
    | '/services/global-capability-center'
    | '/services/it-outsourcing'
    | '/services/it-staffing'
    | '/services/mobile-app-development'
    | '/services/offshore-development'
    | '/services/product-engineering'
    | '/services/software-development'
    | '/services/web-application-development'
    | '/careers'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/awards-achievements'
    | '/careers'
    | '/case-studies'
    | '/contact'
    | '/gallery'
    | '/mission-vision'
    | '/services'
    | '/sitemap.xml'
    | '/team'
    | '/careers/benefits-perks'
    | '/careers/life-at-pure-technology'
    | '/case-studies/$slug'
    | '/hire/$slug'
    | '/hire/ai-developers'
    | '/hire/android-developers'
    | '/hire/backend-developers'
    | '/hire/bolt-new-ai-developers'
    | '/hire/chatbot-developers'
    | '/hire/chatgpt-developers'
    | '/hire/cursor-ai-developers'
    | '/hire/devops-developers'
    | '/hire/frontend-developers'
    | '/hire/fullstack-developers'
    | '/hire/gemini-developers'
    | '/hire/generative-ai-developers'
    | '/hire/google-antigravity-developers'
    | '/hire/lovable-ai-developers'
    | '/hire/mobile-app-developer'
    | '/hire/openai-developers'
    | '/hire/prompt-engineer'
    | '/hire/replit-ai-developers'
    | '/hire/software-developer'
    | '/hire/web-app-developer'
    | '/hire/windsurf-ai-developers'
    | '/services/$slug'
    | '/services/ai-agents-development'
    | '/services/ai-chatbot-development'
    | '/services/ai-integration'
    | '/services/ai-solutions'
    | '/services/cloud-computing'
    | '/services/cloud-infrastructure'
    | '/services/custom-ai-development'
    | '/services/cybersecurity'
    | '/services/data-engineering'
    | '/services/front-end-development'
    | '/services/generative-ai-development'
    | '/services/global-capability-center'
    | '/services/it-outsourcing'
    | '/services/it-staffing'
    | '/services/mobile-app-development'
    | '/services/offshore-development'
    | '/services/product-engineering'
    | '/services/software-development'
    | '/services/web-application-development'
    | '/careers/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AwardsAchievementsRoute: typeof AwardsAchievementsRoute
  CareersRoute: typeof CareersRouteWithChildren
  CaseStudiesRoute: typeof CaseStudiesRouteWithChildren
  ContactRoute: typeof ContactRoute
  GalleryRoute: typeof GalleryRoute
  MissionVisionRoute: typeof MissionVisionRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TeamRoute: typeof TeamRoute
  HireSlugRoute: typeof HireSlugRoute
  HireAiDevelopersRoute: typeof HireAiDevelopersRoute
  HireAndroidDevelopersRoute: typeof HireAndroidDevelopersRoute
  HireBackendDevelopersRoute: typeof HireBackendDevelopersRoute
  HireBoltNewAiDevelopersRoute: typeof HireBoltNewAiDevelopersRoute
  HireChatbotDevelopersRoute: typeof HireChatbotDevelopersRoute
  HireChatgptDevelopersRoute: typeof HireChatgptDevelopersRoute
  HireCursorAiDevelopersRoute: typeof HireCursorAiDevelopersRoute
  HireDevopsDevelopersRoute: typeof HireDevopsDevelopersRoute
  HireFrontendDevelopersRoute: typeof HireFrontendDevelopersRoute
  HireFullstackDevelopersRoute: typeof HireFullstackDevelopersRoute
  HireGeminiDevelopersRoute: typeof HireGeminiDevelopersRoute
  HireGenerativeAiDevelopersRoute: typeof HireGenerativeAiDevelopersRoute
  HireGoogleAntigravityDevelopersRoute: typeof HireGoogleAntigravityDevelopersRoute
  HireLovableAiDevelopersRoute: typeof HireLovableAiDevelopersRoute
  HireMobileAppDeveloperRoute: typeof HireMobileAppDeveloperRoute
  HireOpenaiDevelopersRoute: typeof HireOpenaiDevelopersRoute
  HirePromptEngineerRoute: typeof HirePromptEngineerRoute
  HireReplitAiDevelopersRoute: typeof HireReplitAiDevelopersRoute
  HireSoftwareDeveloperRoute: typeof HireSoftwareDeveloperRoute
  HireWebAppDeveloperRoute: typeof HireWebAppDeveloperRoute
  HireWindsurfAiDevelopersRoute: typeof HireWindsurfAiDevelopersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/team': {
      id: '/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof TeamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-vision': {
      id: '/mission-vision'
      path: '/mission-vision'
      fullPath: '/mission-vision'
      preLoaderRoute: typeof MissionVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies': {
      id: '/case-studies'
      path: '/case-studies'
      fullPath: '/case-studies'
      preLoaderRoute: typeof CaseStudiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/awards-achievements': {
      id: '/awards-achievements'
      path: '/awards-achievements'
      fullPath: '/awards-achievements'
      preLoaderRoute: typeof AwardsAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/careers/': {
      id: '/careers/'
      path: '/'
      fullPath: '/careers/'
      preLoaderRoute: typeof CareersIndexRouteImport
      parentRoute: typeof CareersRoute
    }
    '/services/web-application-development': {
      id: '/services/web-application-development'
      path: '/web-application-development'
      fullPath: '/services/web-application-development'
      preLoaderRoute: typeof ServicesWebApplicationDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/software-development': {
      id: '/services/software-development'
      path: '/software-development'
      fullPath: '/services/software-development'
      preLoaderRoute: typeof ServicesSoftwareDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/product-engineering': {
      id: '/services/product-engineering'
      path: '/product-engineering'
      fullPath: '/services/product-engineering'
      preLoaderRoute: typeof ServicesProductEngineeringRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/offshore-development': {
      id: '/services/offshore-development'
      path: '/offshore-development'
      fullPath: '/services/offshore-development'
      preLoaderRoute: typeof ServicesOffshoreDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/mobile-app-development': {
      id: '/services/mobile-app-development'
      path: '/mobile-app-development'
      fullPath: '/services/mobile-app-development'
      preLoaderRoute: typeof ServicesMobileAppDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/it-staffing': {
      id: '/services/it-staffing'
      path: '/it-staffing'
      fullPath: '/services/it-staffing'
      preLoaderRoute: typeof ServicesItStaffingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/it-outsourcing': {
      id: '/services/it-outsourcing'
      path: '/it-outsourcing'
      fullPath: '/services/it-outsourcing'
      preLoaderRoute: typeof ServicesItOutsourcingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/global-capability-center': {
      id: '/services/global-capability-center'
      path: '/global-capability-center'
      fullPath: '/services/global-capability-center'
      preLoaderRoute: typeof ServicesGlobalCapabilityCenterRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/generative-ai-development': {
      id: '/services/generative-ai-development'
      path: '/generative-ai-development'
      fullPath: '/services/generative-ai-development'
      preLoaderRoute: typeof ServicesGenerativeAiDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/front-end-development': {
      id: '/services/front-end-development'
      path: '/front-end-development'
      fullPath: '/services/front-end-development'
      preLoaderRoute: typeof ServicesFrontEndDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/data-engineering': {
      id: '/services/data-engineering'
      path: '/data-engineering'
      fullPath: '/services/data-engineering'
      preLoaderRoute: typeof ServicesDataEngineeringRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cybersecurity': {
      id: '/services/cybersecurity'
      path: '/cybersecurity'
      fullPath: '/services/cybersecurity'
      preLoaderRoute: typeof ServicesCybersecurityRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/custom-ai-development': {
      id: '/services/custom-ai-development'
      path: '/custom-ai-development'
      fullPath: '/services/custom-ai-development'
      preLoaderRoute: typeof ServicesCustomAiDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cloud-infrastructure': {
      id: '/services/cloud-infrastructure'
      path: '/cloud-infrastructure'
      fullPath: '/services/cloud-infrastructure'
      preLoaderRoute: typeof ServicesCloudInfrastructureRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cloud-computing': {
      id: '/services/cloud-computing'
      path: '/cloud-computing'
      fullPath: '/services/cloud-computing'
      preLoaderRoute: typeof ServicesCloudComputingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ai-solutions': {
      id: '/services/ai-solutions'
      path: '/ai-solutions'
      fullPath: '/services/ai-solutions'
      preLoaderRoute: typeof ServicesAiSolutionsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ai-integration': {
      id: '/services/ai-integration'
      path: '/ai-integration'
      fullPath: '/services/ai-integration'
      preLoaderRoute: typeof ServicesAiIntegrationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ai-chatbot-development': {
      id: '/services/ai-chatbot-development'
      path: '/ai-chatbot-development'
      fullPath: '/services/ai-chatbot-development'
      preLoaderRoute: typeof ServicesAiChatbotDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ai-agents-development': {
      id: '/services/ai-agents-development'
      path: '/ai-agents-development'
      fullPath: '/services/ai-agents-development'
      preLoaderRoute: typeof ServicesAiAgentsDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/hire/windsurf-ai-developers': {
      id: '/hire/windsurf-ai-developers'
      path: '/hire/windsurf-ai-developers'
      fullPath: '/hire/windsurf-ai-developers'
      preLoaderRoute: typeof HireWindsurfAiDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/web-app-developer': {
      id: '/hire/web-app-developer'
      path: '/hire/web-app-developer'
      fullPath: '/hire/web-app-developer'
      preLoaderRoute: typeof HireWebAppDeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/software-developer': {
      id: '/hire/software-developer'
      path: '/hire/software-developer'
      fullPath: '/hire/software-developer'
      preLoaderRoute: typeof HireSoftwareDeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/replit-ai-developers': {
      id: '/hire/replit-ai-developers'
      path: '/hire/replit-ai-developers'
      fullPath: '/hire/replit-ai-developers'
      preLoaderRoute: typeof HireReplitAiDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/prompt-engineer': {
      id: '/hire/prompt-engineer'
      path: '/hire/prompt-engineer'
      fullPath: '/hire/prompt-engineer'
      preLoaderRoute: typeof HirePromptEngineerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/openai-developers': {
      id: '/hire/openai-developers'
      path: '/hire/openai-developers'
      fullPath: '/hire/openai-developers'
      preLoaderRoute: typeof HireOpenaiDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/mobile-app-developer': {
      id: '/hire/mobile-app-developer'
      path: '/hire/mobile-app-developer'
      fullPath: '/hire/mobile-app-developer'
      preLoaderRoute: typeof HireMobileAppDeveloperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/lovable-ai-developers': {
      id: '/hire/lovable-ai-developers'
      path: '/hire/lovable-ai-developers'
      fullPath: '/hire/lovable-ai-developers'
      preLoaderRoute: typeof HireLovableAiDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/google-antigravity-developers': {
      id: '/hire/google-antigravity-developers'
      path: '/hire/google-antigravity-developers'
      fullPath: '/hire/google-antigravity-developers'
      preLoaderRoute: typeof HireGoogleAntigravityDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/generative-ai-developers': {
      id: '/hire/generative-ai-developers'
      path: '/hire/generative-ai-developers'
      fullPath: '/hire/generative-ai-developers'
      preLoaderRoute: typeof HireGenerativeAiDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/gemini-developers': {
      id: '/hire/gemini-developers'
      path: '/hire/gemini-developers'
      fullPath: '/hire/gemini-developers'
      preLoaderRoute: typeof HireGeminiDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/fullstack-developers': {
      id: '/hire/fullstack-developers'
      path: '/hire/fullstack-developers'
      fullPath: '/hire/fullstack-developers'
      preLoaderRoute: typeof HireFullstackDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/frontend-developers': {
      id: '/hire/frontend-developers'
      path: '/hire/frontend-developers'
      fullPath: '/hire/frontend-developers'
      preLoaderRoute: typeof HireFrontendDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/devops-developers': {
      id: '/hire/devops-developers'
      path: '/hire/devops-developers'
      fullPath: '/hire/devops-developers'
      preLoaderRoute: typeof HireDevopsDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/cursor-ai-developers': {
      id: '/hire/cursor-ai-developers'
      path: '/hire/cursor-ai-developers'
      fullPath: '/hire/cursor-ai-developers'
      preLoaderRoute: typeof HireCursorAiDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/chatgpt-developers': {
      id: '/hire/chatgpt-developers'
      path: '/hire/chatgpt-developers'
      fullPath: '/hire/chatgpt-developers'
      preLoaderRoute: typeof HireChatgptDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/chatbot-developers': {
      id: '/hire/chatbot-developers'
      path: '/hire/chatbot-developers'
      fullPath: '/hire/chatbot-developers'
      preLoaderRoute: typeof HireChatbotDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/bolt-new-ai-developers': {
      id: '/hire/bolt-new-ai-developers'
      path: '/hire/bolt-new-ai-developers'
      fullPath: '/hire/bolt-new-ai-developers'
      preLoaderRoute: typeof HireBoltNewAiDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/backend-developers': {
      id: '/hire/backend-developers'
      path: '/hire/backend-developers'
      fullPath: '/hire/backend-developers'
      preLoaderRoute: typeof HireBackendDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/android-developers': {
      id: '/hire/android-developers'
      path: '/hire/android-developers'
      fullPath: '/hire/android-developers'
      preLoaderRoute: typeof HireAndroidDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/ai-developers': {
      id: '/hire/ai-developers'
      path: '/hire/ai-developers'
      fullPath: '/hire/ai-developers'
      preLoaderRoute: typeof HireAiDevelopersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hire/$slug': {
      id: '/hire/$slug'
      path: '/hire/$slug'
      fullPath: '/hire/$slug'
      preLoaderRoute: typeof HireSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/case-studies/$slug': {
      id: '/case-studies/$slug'
      path: '/$slug'
      fullPath: '/case-studies/$slug'
      preLoaderRoute: typeof CaseStudiesSlugRouteImport
      parentRoute: typeof CaseStudiesRoute
    }
    '/careers/life-at-pure-technology': {
      id: '/careers/life-at-pure-technology'
      path: '/life-at-pure-technology'
      fullPath: '/careers/life-at-pure-technology'
      preLoaderRoute: typeof CareersLifeAtPureTechnologyRouteImport
      parentRoute: typeof CareersRoute
    }
    '/careers/benefits-perks': {
      id: '/careers/benefits-perks'
      path: '/benefits-perks'
      fullPath: '/careers/benefits-perks'
      preLoaderRoute: typeof CareersBenefitsPerksRouteImport
      parentRoute: typeof CareersRoute
    }
  }
}

interface CareersRouteChildren {
  CareersBenefitsPerksRoute: typeof CareersBenefitsPerksRoute
  CareersLifeAtPureTechnologyRoute: typeof CareersLifeAtPureTechnologyRoute
  CareersIndexRoute: typeof CareersIndexRoute
}

const CareersRouteChildren: CareersRouteChildren = {
  CareersBenefitsPerksRoute: CareersBenefitsPerksRoute,
  CareersLifeAtPureTechnologyRoute: CareersLifeAtPureTechnologyRoute,
  CareersIndexRoute: CareersIndexRoute,
}

const CareersRouteWithChildren =
  CareersRoute._addFileChildren(CareersRouteChildren)

interface CaseStudiesRouteChildren {
  CaseStudiesSlugRoute: typeof CaseStudiesSlugRoute
}

const CaseStudiesRouteChildren: CaseStudiesRouteChildren = {
  CaseStudiesSlugRoute: CaseStudiesSlugRoute,
}

const CaseStudiesRouteWithChildren = CaseStudiesRoute._addFileChildren(
  CaseStudiesRouteChildren,
)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesAiAgentsDevelopmentRoute: typeof ServicesAiAgentsDevelopmentRoute
  ServicesAiChatbotDevelopmentRoute: typeof ServicesAiChatbotDevelopmentRoute
  ServicesAiIntegrationRoute: typeof ServicesAiIntegrationRoute
  ServicesAiSolutionsRoute: typeof ServicesAiSolutionsRoute
  ServicesCloudComputingRoute: typeof ServicesCloudComputingRoute
  ServicesCloudInfrastructureRoute: typeof ServicesCloudInfrastructureRoute
  ServicesCustomAiDevelopmentRoute: typeof ServicesCustomAiDevelopmentRoute
  ServicesCybersecurityRoute: typeof ServicesCybersecurityRoute
  ServicesDataEngineeringRoute: typeof ServicesDataEngineeringRoute
  ServicesFrontEndDevelopmentRoute: typeof ServicesFrontEndDevelopmentRoute
  ServicesGenerativeAiDevelopmentRoute: typeof ServicesGenerativeAiDevelopmentRoute
  ServicesGlobalCapabilityCenterRoute: typeof ServicesGlobalCapabilityCenterRoute
  ServicesItOutsourcingRoute: typeof ServicesItOutsourcingRoute
  ServicesItStaffingRoute: typeof ServicesItStaffingRoute
  ServicesMobileAppDevelopmentRoute: typeof ServicesMobileAppDevelopmentRoute
  ServicesOffshoreDevelopmentRoute: typeof ServicesOffshoreDevelopmentRoute
  ServicesProductEngineeringRoute: typeof ServicesProductEngineeringRoute
  ServicesSoftwareDevelopmentRoute: typeof ServicesSoftwareDevelopmentRoute
  ServicesWebApplicationDevelopmentRoute: typeof ServicesWebApplicationDevelopmentRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesAiAgentsDevelopmentRoute: ServicesAiAgentsDevelopmentRoute,
  ServicesAiChatbotDevelopmentRoute: ServicesAiChatbotDevelopmentRoute,
  ServicesAiIntegrationRoute: ServicesAiIntegrationRoute,
  ServicesAiSolutionsRoute: ServicesAiSolutionsRoute,
  ServicesCloudComputingRoute: ServicesCloudComputingRoute,
  ServicesCloudInfrastructureRoute: ServicesCloudInfrastructureRoute,
  ServicesCustomAiDevelopmentRoute: ServicesCustomAiDevelopmentRoute,
  ServicesCybersecurityRoute: ServicesCybersecurityRoute,
  ServicesDataEngineeringRoute: ServicesDataEngineeringRoute,
  ServicesFrontEndDevelopmentRoute: ServicesFrontEndDevelopmentRoute,
  ServicesGenerativeAiDevelopmentRoute: ServicesGenerativeAiDevelopmentRoute,
  ServicesGlobalCapabilityCenterRoute: ServicesGlobalCapabilityCenterRoute,
  ServicesItOutsourcingRoute: ServicesItOutsourcingRoute,
  ServicesItStaffingRoute: ServicesItStaffingRoute,
  ServicesMobileAppDevelopmentRoute: ServicesMobileAppDevelopmentRoute,
  ServicesOffshoreDevelopmentRoute: ServicesOffshoreDevelopmentRoute,
  ServicesProductEngineeringRoute: ServicesProductEngineeringRoute,
  ServicesSoftwareDevelopmentRoute: ServicesSoftwareDevelopmentRoute,
  ServicesWebApplicationDevelopmentRoute:
    ServicesWebApplicationDevelopmentRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AwardsAchievementsRoute: AwardsAchievementsRoute,
  CareersRoute: CareersRouteWithChildren,
  CaseStudiesRoute: CaseStudiesRouteWithChildren,
  ContactRoute: ContactRoute,
  GalleryRoute: GalleryRoute,
  MissionVisionRoute: MissionVisionRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TeamRoute: TeamRoute,
  HireSlugRoute: HireSlugRoute,
  HireAiDevelopersRoute: HireAiDevelopersRoute,
  HireAndroidDevelopersRoute: HireAndroidDevelopersRoute,
  HireBackendDevelopersRoute: HireBackendDevelopersRoute,
  HireBoltNewAiDevelopersRoute: HireBoltNewAiDevelopersRoute,
  HireChatbotDevelopersRoute: HireChatbotDevelopersRoute,
  HireChatgptDevelopersRoute: HireChatgptDevelopersRoute,
  HireCursorAiDevelopersRoute: HireCursorAiDevelopersRoute,
  HireDevopsDevelopersRoute: HireDevopsDevelopersRoute,
  HireFrontendDevelopersRoute: HireFrontendDevelopersRoute,
  HireFullstackDevelopersRoute: HireFullstackDevelopersRoute,
  HireGeminiDevelopersRoute: HireGeminiDevelopersRoute,
  HireGenerativeAiDevelopersRoute: HireGenerativeAiDevelopersRoute,
  HireGoogleAntigravityDevelopersRoute: HireGoogleAntigravityDevelopersRoute,
  HireLovableAiDevelopersRoute: HireLovableAiDevelopersRoute,
  HireMobileAppDeveloperRoute: HireMobileAppDeveloperRoute,
  HireOpenaiDevelopersRoute: HireOpenaiDevelopersRoute,
  HirePromptEngineerRoute: HirePromptEngineerRoute,
  HireReplitAiDevelopersRoute: HireReplitAiDevelopersRoute,
  HireSoftwareDeveloperRoute: HireSoftwareDeveloperRoute,
  HireWebAppDeveloperRoute: HireWebAppDeveloperRoute,
  HireWindsurfAiDevelopersRoute: HireWindsurfAiDevelopersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
